### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by a-c-m** [noitcudni/google-webmaster-tools-bulk-url-removal#1]
Just a quick thank you.

I had to remove 160 urls from google, this stopped me getting RSI.

**Comment by noitcudni** [comment]
Glad to hear that you found it useful. Btw, what's RSI? Also, just FYI, in
30 days or so those removed urls will come back. Make sure that you add
those urls to your robots.txt.

Lih

**Comment by uaibo** [comment]
you just saved me a whole lot of boring time. I had to remove 150+ urls. So thaaaaanks a lot, great tool :)
