### ISSUE TITLE
License??

### ISSUE THREAD

**Issue by michelelang** [noitcudni/google-webmaster-tools-bulk-url-removal#100]
I purchased both of your extensions awhile ago and now they are asking for my license - but I don't know where to find this?
![Screen Shot 2020-12-21 at 3 16 14 PM](https://user-images.githubusercontent.com/34300727/102786393-b62a0400-439f-11eb-8d3f-1c59467a7f16.png)
![Screen Shot 2020-12-21 at 3 16 31 PM](https://user-images.githubusercontent.com/34300727/102786397-b75b3100-439f-11eb-90ec-a4e57d046455.png)

**Comment by noitcudni** [comment]
Please email me directly at lihster.developer@gmail.com. I'll take care of it.

**Comment by noitcudni** [comment]
Resolved.
