### ISSUE TITLE
it's not showing me file upload option

### ISSUE THREAD

**Issue by leahowen001** [noitcudni/google-webmaster-tools-bulk-url-removal#102]
hi it's not showing me file upload option

**Comment by noitcudni** [comment]
What is it showing you? Please attach a screenshot

**Comment by noitcudni** [comment]
you can also email me directly at lihster.developer@gmail.com

**Comment by mrwasi96** [comment]
Hi It is not working in my browser.   screenshot attached:

Error is
(
 **"Failed to load extension
File
~\Desktop\google-search-console-bulk-url-removal-master
Error
Manifest file is missing or unreadable
Could not load manifest."**
)
![image](https://user-images.githubusercontent.com/79806729/109500825-90fcf480-7ab8-11eb-97a4-78562d4b9c93.png)

**Comment by restre** [comment]
Having the problem...

"Manifest file is missing or unreadable"

I need to use this tool fast

Please help
