### ISSUE TITLE
Gets hung after uploading csv file 

### ISSUE THREAD

**Issue by bwagner182** [noitcudni/google-webmaster-tools-bulk-url-removal#103]
Running Chrome 87
MacOS 11.0.1

I tried uploading just a small batch of the links I need removed and I've seen the suggestions on other issues to refresh the page, clear the cache, and inspect the extension and get the console output. It seems to go through the file fine and sanitize the data and then it reads "about to call :init-victims" and nothing seems to happen.

**Comment by noitcudni** [comment]
Did you compile the code yourself? Or, is this a purchased version?

Can you send me your csv file to lihster.developer@gmail.com?

**Comment by bwagner182** [comment]
Compiled it myself. Sent the csv file your way as well.

**Comment by noitcudni** [comment]
Was able to reproduce.
Interesting. It appears that I have to handle `::runtime/on-installed`, or else it gets angry. 
Please pull from master, recompile and reload your extension.
