### ISSUE TITLE
Access code not working

### ISSUE THREAD

**Issue by EdKoala** [noitcudni/google-webmaster-tools-bulk-url-removal#104]
Hi I used the plugin successfully last month. I tried renewing membership which didn't work, Then i deleted the extension and purchased a membership again and reinstalled the extension. No matter what I try the new key code isn't being accepted. 
Please advise

**Comment by noitcudni** [comment]
You don't need to renew a membership. It's a recurring monthly subscription. It should happen automatically. Let's move this discussion over email. Please email me at lihster.developer@gmail.com along with your account info, ie. the email you used to sign up for the first time and second time.
