### ISSUE TITLE
Restoring purchases - previously bought both applications on Chrome store

### ISSUE THREAD

**Issue by advancedperiodontics** [noitcudni/google-webmaster-tools-bulk-url-removal#105]
Hi, I've tried to use this application after some time not using it and am now prompted for a gumroad key.  I purchased both extensions from the chrome web store.  Can my purchase be restored?  Proof that i owned the application previously: https://github.com/noitcudni/google-search-console-bulk-url-removal/issues/50#issue-556253434

**Comment by noitcudni** [comment]
Can you ping me directly at lihster.developer@gmail.com? I'll take care of it.
