### ISSUE TITLE
optional-columns.csv looks decieving

### ISSUE THREAD

**Issue by frankfuu** [noitcudni/google-webmaster-tools-bulk-url-removal#106]
I just had to manually remove 400 urls by hand because I tried to follow the format of the sample CSV named "optional-columns.csv".

![image](https://user-images.githubusercontent.com/7758528/113669952-d33cd580-96f7-11eb-8839-6cb01bb14773.png)

I was wanting to use the optional parameter "clear-cached" rather than the default "remove-url" so tried to follow the format in the CSV file (optional-columns.csv) using Microsoft Excel but it didn't work. I later realised I had to put the optional param into another column as opposed to appending a comma

**Comment by frankfuu** [comment]
I might add that if you are using a text editor like sublime text etc, this wouldn't be a problem ;) but I thought i might point this out for the other poor souls who may have stepped into the same path.

**Comment by noitcudni** [comment]
If you want to use excel, you probably need to tell it that it's a csv file with the comma delimiter.

Yes, if you use sublime (I use vim), this wouldn't have been a problem. However, the majority of users don't code.

**Comment by frankfuu** [comment]
>However, the majority of users don't code.

This is exactly why I've raised this as an issue. The majority of the users using this are people who do not code and could be easily fooled if they opened the **example2** csv file via Excel provided in this Chrome Extension thinking they would need to append the comma after their URL in the same column. Just my two cents, feel free to ignore.

![image](https://user-images.githubusercontent.com/7758528/113785667-ef358b00-977a-11eb-8d92-081cd13d93be.png)
