### ISSUE TITLE
csv URL character encoding damaged after upload

### ISSUE THREAD

**Issue by PressHero** [noitcudni/google-webmaster-tools-bulk-url-removal#107]
Using English Language 

I export the csv file from search console > coverage

upload to google drive, remove the date columns

Then save as csv

Go to Removals

Click Submit CSV File

All rows cause an error, "Not in property" due to the character encoding changing.

For example a URL will be converted incorrectly:

~ݰ�

The URL text appears fine in the file, only after upload there is an issue. 

Any suggestions.

Thanks

**Comment by noitcudni** [comment]
I have seen something like this in the past, except that it didn't trigger a "Not in property" error. The resulting urls listed in the table weren't encoded properly. However, they did get removed.

Can you email me your csv file to lihster.developer@gmail.com?

**Comment by PressHero** [comment]
Here is a copy. Let me know what you find. Have 32k bad links to clean up
from a hack.

Thanks for the quick response.

Rob

**Comment by noitcudni** [comment]
I'm not seeing the file in github. Can you email it to me at lihster.developer@gmail.com?

**Comment by PressHero** [comment]
Attached to last email

**Comment by noitcudni** [comment]
Nope. No attachment. You'll have to email it to me.

**Comment by noitcudni** [comment]
Looks like github drops the attachment on the floor.

**Comment by PressHero** [comment]
Ok one sec. I'll send a Google drive link

**Comment by PressHero** [comment]
What's your direct email? (I won't share)

**Comment by noitcudni** [comment]
Looks like github obfuscate emails, too. You should be able to find me email on my profile page. https://github.com/noitcudni
If all fails, you can just pick a handful of urls and paste them in here.
