### ISSUE TITLE
30000 links 

### ISSUE THREAD

**Issue by nejerfan** [noitcudni/google-webmaster-tools-bulk-url-removal#109]
please if i have 30000 links how can i download them from google console because it show just last 1000 links

**Comment by noitcudni** [comment]
I believe that Google Search Console only lets you download 1000 links. By the way, when it comes to url removal, Google Search Console also limits you 1000 removal per 24 hours. I think you could probably just download the first 1000 and remove them. Wait 24 hours. download the next 1000 and remove those. Repeat.

**Comment by noitcudni** [comment]
Do you mind sharing with me the domain name?
