### ISSUE TITLE
How to remove 400K URLs?

### ISSUE THREAD

**Issue by evyatarGill** [noitcudni/google-webmaster-tools-bulk-url-removal#110]
Hi,
I have an 400K efected pages that Indexed, not submitted in sitemap.
When I am exporting the CSV file from GSC I can see only 1K rows
why is that?
I tried to bulk remove them with your extention but it seems that there insnt remove all the 400K pages.
Wish for your best edvice for my senario.

**Comment by noitcudni** [comment]
Unfortunately, GCS will only allow you to download one thousand urls. Do you have another way of getting the full list of affected urls?

GCS imposes a 24 hour quota of 1000 urls to be removed. What's the nature of hack you are facing? If you don't feel comfortable posting it on github. Feel feel to email me directly at lihster.developer@gmail.com
