### ISSUE TITLE
Uncaught Error: No matching clause: chromex.ext.runtime/on-installed

### ISSUE THREAD

**Issue by khanakia** [noitcudni/google-webmaster-tools-bulk-url-removal#111]
I just compiled and installed the latest version of the extension and not working

<img width="753" alt="Screenshot 2021-11-15 at 6 04 58 PM" src="https://user-images.githubusercontent.com/2174170/141783093-ccbb784d-2f86-47cc-a313-906c830d04b3.png">
.

**Comment by tprinty** [comment]
I have this same error when loading the extension from the extension console. 
Ran lein on a Ubuntu machine

**Comment by khanakia** [comment]
@tprinty anyway i built my on script using Selenium IDE and that worked perfectly

**Comment by noitcudni** [comment]
@khanakia Good to hear that you got it working with Selenium. 
@tprinty Please ping me at lihster.developer@gmail.com
