### ISSUE TITLE
Lost focus on execution TAB

### ISSUE THREAD

**Issue by Stonetatara** [noitcudni/google-webmaster-tools-bulk-url-removal#113]
Hello,
i'm using the self install script (not the Chrome Plugin), it's working fine.
I've a comment about the lost of focus when you change the tab where the script is running, I'll try to be clear...

You run the script in tab A, you open a second tab B to surf on another site while the script is running.
As soon as you change tabs, I have the impression that the script does not progress any more: it always stays on the same url to be processed. 

As soon as you stay on the tab, the script runs and continues to process the remaining urls of the CSV file.

If you don't have a second screen, this forces you to stay on the tab while the script finishes processing all the urls.
Are you aware of this? Is there any way to fix this?

Thank you for your help

**Comment by noitcudni** [comment]
Yup, I'm aware of this. This is because it's automating user actions. You'll have to use a different browser
