### ISSUE TITLE
Submit CVC File Button Not working

### ISSUE THREAD

**Issue by techmaish** [noitcudni/google-webmaster-tools-bulk-url-removal#115]
Hi. 

When I click on the button "Submit CVC File" the file attachment window does not appear.

I am already on the URL Removal Page for the particular domain but still the button is not working.

Kindly guide me on this.

**Comment by noitcudni** [comment]
Did you purchase the extension from Chrome Webstore?
Which version of Chrome are you using?

**Comment by techmaish** [comment]
I am using Chromium. 

I used the "Buy Now" button on the extension and subscribed and received license key.

**Comment by noitcudni** [comment]
Got it. I had another user using Chromium running into the same issue.
If I remember correctly, the latest "stable" Chromium doesn't support the
new manifest v3.
I have migrated my extension to manifest v3.
To fix the problem, upgrade your Chromium. Or, use Chrome.

**Comment by techmaish** [comment]
It is working fine on Google Chrome. Thanks.
How many URLs this tool can submit? Or how many URLs google allow to be submitted.

**Comment by techmaish** [comment]
Can the tool restart the process from the same URL where the process was stopped. I changed the window and the tool stopped. Now after restarting the process will this skip the URLs that are already submitted?

**Comment by noitcudni** [comment]
The list of URLs is cached. It should pick up where it left off.

There's a 1000 limit per 24 hours imposed by Google Search Console.

**Comment by techmaish** [comment]
Ok thank you.

By the way, I tried resubmitting the file but it started submitting the same URLs again and Search Console was giving error that One URL should be submitted once.

Anyways, I just deleted the already submitted URLs from the File and then restarted the process. It then worked.
