### ISSUE TITLE
I made a purchase but my password keeps showing incorrectly and I changed it several times l

### ISSUE THREAD

**Issue by BULULU1** [noitcudni/google-webmaster-tools-bulk-url-removal#117]
I made a purchase but my password keeps showing incorrectly and I changed it several times l

**Comment by noitcudni** [comment]
Can you try uninstalling and reinstalling the extension?

**Comment by BULULU1** [comment]
How to cancel the subscription, I just want to buy one month

**Comment by noitcudni** [comment]
The email with your license should have a link. That reads manage your
membership or something like that. You can cancel from there.
