### ISSUE TITLE
Submit button not working

### ISSUE THREAD

**Issue by svreatt** [noitcudni/google-webmaster-tools-bulk-url-removal#119]
I purchased your extension today and it will not allow me to upload an cvs file. I am using the latest version of chrome on a mac computer.

**Comment by noitcudni** [comment]
Did you try refreshing the page?

**Comment by svreatt** [comment]
Yes, I even restarted google.

**Comment by noitcudni** [comment]
Can you copy and paste the chrome version here? You can get to it by
visiting chrome://version/ in your browser.

I'll take a look tonight.

**Comment by svreatt** [comment]
Google Chrome | 103.0.5060.114 (Official Build) (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 10.15.7 (Build 19H1922)

**Comment by svreatt** [comment]
Now it will let me upload a cvs file, but the window closes and nothing happens.  I tried your fix of inspecting the window, but it didn't work either.

**Comment by svreatt** [comment]
I did get the upload button to work. Now once the cvs file is uploaded, nothing happens. I did try inspecting the popup window, but that didn’t work either.

**Comment by noitcudni** [comment]
I just updated my chrome to the latest version, and it works for me. Do you
mind sending a screencast video of what you are experiencing to my email:
lihster.developer@gmail.com. Below is my chrome version on my mac.
Google Chrome 103.0.5060.114 (Official Build) (x86_64)
Revision a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@
{#1124}

**Comment by svreatt** [comment]
I figured out how to get the software to run. I had to manually enter one page removal after uploading the cvs file and then the software started running.

I have a question about the clear cache button. When I click it nothing happens. Is this supposed to clear the indexed pages cache?

Thanks

**Comment by noitcudni** [comment]
Yes, you have to be on the url removal page as stated in the instructions.
I'm glad it's working for you.

Sometimes the extension gets into a weird state, the clear cache button
clears all the internal cached data to start anew.
Normally, you don't need to press that.
