### ISSUE TITLE
No License Key

### ISSUE THREAD

**Issue by bbyrnemodulim** [noitcudni/google-webmaster-tools-bulk-url-removal#120]
I didn't receive a license key after my purchase. I would like to cancel my purchase as I cannot wait any longer and have decided to do this process manually

**Comment by bbyrnemodulim** [comment]
@noitcudni I never received my license key for this extension. I manually deleted all the URLs I needed to delete. Please refund my $15 as I didn't have access to use the extension.

**Comment by noitcudni** [comment]
Oops. Sorry, I totally didn't see this. I'll refund you. Is it possible to
remove your one star rating on gumroad?

**Comment by bbyrnemodulim** [comment]
Thank you. I will gladly remove my one  star rating if you can point me to the webpage that would allow me to adjust it

__________
Blake Byrne
Director of Marketing
Office: 949-825-5095
Modulim<https://modulim.com/> | 2400 Barranca Parkway | Irvine | CA 92606

**Comment by noitcudni** [comment]
https://noitcudni.gumroad.com/l/Mdwjw

**Comment by noitcudni** [comment]
Also, I resent you a receipt. Maybe you can do it from there.

**Comment by bbyrnemodulim** [comment]
@noitcudni It does not allow me to edit the rating on that page. I think because I am no longer a subscriber?
