### ISSUE TITLE
Stuck on submitting request pop-up

### ISSUE THREAD

**Issue by Tech-MSS** [noitcudni/google-webmaster-tools-bulk-url-removal#121]
Hello, 

We purchased a licensed and started to use it however we weren't able to use it successfully. 

We got an error in the console and the popup stuck on Submitting Request. 

![bulk url removal extension hangs on submitting request - error attached 2](https://user-images.githubusercontent.com/113245660/189485079-54fea3bf-b81b-4558-991e-d129dc8c4bd5.jpg)

I tried to reload and tried again. 
After 2-3 submissions, it always became like that.

**Comment by noitcudni** [comment]
Hi, I believe that I encountered this error when somehow another extension
interferes with my extension.

Can you do me a favor? For now disable all extensions but mine. Reload the
page and try again?

Also, what version of Chrome are you using?
Lih

**Comment by Tech-MSS** [comment]
Hi Lih, 

You are right, the other extensions are causing the issue. 
You plugin works fine after disabling them. 

Appreciate your help!
Thank you!
