### ISSUE TITLE
License Key is Not Received 

### ISSUE THREAD

**Issue by abd320** [noitcudni/google-webmaster-tools-bulk-url-removal#122]
Hi Dear,
I hope you are doing well. I pay the subscription fee but didn't receive any confirmation email and license key yet. Please provide me with the license key in order to start my work. Thank You!

**Comment by noitcudni** [comment]
Hi,
Can you ping me directly at ***@***.***? I'll take care of
it.

**Comment by kastriotsula** [comment]
Hello, I bought your extension but can't find the license key. Can you help me out?

**Comment by noitcudni** [comment]
Sorry, it appears that github masked my email.
lihster.developer@gmail.com

**Comment by abd320** [comment]
Hi Dear,
I also approach you on Github. So my issue is resolved now. No issue left
behind. Thank you!
*Regards*


*Muhammad Abdullah*
