### ISSUE TITLE
Licence Key missing

### ISSUE THREAD

**Issue by kastriotsula** [noitcudni/google-webmaster-tools-bulk-url-removal#123]
Hello, I bought your extension but can't find the license key. Can you help me out?

**Comment by noitcudni** [comment]
Can you email me directly at ***@***.***?

**Comment by kastriotsula** [comment]
I don't see your email, i see ******

**Comment by noitcudni** [comment]
Sorry, it appears that github masked my email.
[lihster.developer@gmail.com](mailto:lihster.developer@gmail.com)
