### ISSUE TITLE
licace key missing

### ISSUE THREAD

**Issue by bilalbal34** [noitcudni/google-webmaster-tools-bulk-url-removal#124]
Hello, I bought your extension but can't find the license key. Can you help me out?
Mail:analitik@armadigital.net
<img width="732" alt="Ekran Resmi 2022-12-08 17 54 56" src="https://user-images.githubusercontent.com/120113839/206478698-3c09de95-124c-41f0-8d97-ad838bbcc7dd.png">
payment receipt attached

**Comment by bilalbal34** [comment]
![lisans](https://user-images.githubusercontent.com/120113839/207160024-381fd2f5-e6d1-4c08-ab68-212efc5c6279.png)

**Comment by noitcudni** [comment]
Sure, I'm going to email you directly at analitik at armadigital.com

**Comment by abdelilaheladili** [comment]
hi [noitcudni]

i need license for extension [google-search-console-bulk-url-removal]

**Comment by abdelilaheladili** [comment]
download the zip file from [github](https://github.com/noitcudni/google-webmaster-tools-bulk-url-removal/archive/master.zip) and unzip it.
Because this file is no longer working

**Comment by noitcudni** [comment]
@abdelilaheladili Did you purchase the extension? If so, please email me directly lihster.developer@gmail.com
