### ISSUE TITLE
Google Link removal tool is exiting after only a few links are entered w/ no errors indicated

### ISSUE THREAD

**Issue by AlchemistTim** [noitcudni/google-webmaster-tools-bulk-url-removal#125]
Re-posting after I accidentally posted on the Bing Removal toll area.

A great tool that I have used the tool successfully a few times.

Today it has been failing after only a few operations.

I have included the developer's console logs for your inspection. I am also including the CSV file I am running for the removals.

[search.google.com-1672424851628.log](https://github.com/noitcudni/google-search-console-bulk-url-removal/files/10326477/search.google.com-1672424851628.log)
[Removals_12_30_22.csv](https://github.com/noitcudni/google-search-console-bulk-url-removal/files/10326478/Removals_12_30_22.csv)

**Comment by noitcudni** [comment]
Can you try disabling all the other extensions and give it another go?
Also, don't switch to a different tab while it's running.

**Comment by AlchemistTim** [comment]
I don't use Chrome that much, and this was the only extension I have loaded.
Sensing from your suggestion that outside activities might be upsetting the process, I cold booted, opened only chrome and ran the extension again.
Worked perfectly - 600 URL's removed.

Thanks for the quick response.
