### ISSUE TITLE
No License Key Received 

### ISSUE THREAD

**Issue by AditiAnand1121** [noitcudni/google-webmaster-tools-bulk-url-removal#128]
Hello,  I have made a payment with my email id aditi.anand@smartschoolonline.in but I didn't receive any license key additionally i have subscribed for 1 month only my card has been set for recurring payment

**Comment by AditiAnand1121** [comment]
[Invoice-29297D87-0005.pdf](https://github.com/noitcudni/google-search-console-bulk-url-removal/files/10773832/Invoice-29297D87-0005.pdf)

**Comment by noitcudni** [comment]
This was resolved via email
