### ISSUE TITLE
All URLs going to Error and non gets submitted for removal

### ISSUE THREAD

**Issue by GraphicDOP** [noitcudni/google-webmaster-tools-bulk-url-removal#129]
Hello! Unfortunately all URLs going to to Error and nothing gets submitted for removal, it only works if I manually add urls.
They all ending up in error and only these 11 that I added manually are submitted for removal.
<img width="1241" alt="Screenshot 2566-04-18 at 21 55 07" src="https://user-images.githubusercontent.com/93442419/232903655-6841a01a-1b56-4814-be70-46de0a7517ef.png">

**Comment by noitcudni** [comment]
Please refer to https://github.com/noitcudni/google-search-console-bulk-url-removal#csv-format.

Basically, you have an extra column. You can also click on the download error CSV button and see what the errors were.
