### ISSUE TITLE
Unable to upload CSV file

### ISSUE THREAD

**Issue by karldavidson182** [noitcudni/google-webmaster-tools-bulk-url-removal#130]
Hi Team, 

I've recently downloaded the Chrome extension but having some issues uploading my CSV file. I've followed the steps, but when I click "Submit CSV file", nothing happens. 

Here is a video recording to show you what I'm experiencing - https://www.loom.com/share/74f599534ee246f686ecccf2d90465fc

Any help would be appreciated. 

Thanks.

**Comment by noitcudni** [comment]
You don't need to click on the "New Request" button prior to click on the "Submit CSV file" button. 
Also, try disabling other extensions for now and refresh the page and see if that works.

**Comment by l3luel3l00d** [comment]
Got exactly the same problem since a few weeks now. Randomly it works again sometimes...

**Comment by noitcudni** [comment]
Try this. Make sure that you only have one browser window. You can have multiple tabs open but make sure that you only have one browser window. Now try using the extension. The submit button should work. One the extension starts doing its thing, you can drag the tab out into its own window.

Next drag the tab that has Google Search Console open. Now the submit button shouldn't work.

I think that there's a bug with the Chrome extension API. I might be able to come up with a work around in code, but I've been preoccupied with other stuff the last couple weeks. I'll look into this soon.

**Comment by l3luel3l00d** [comment]
Yes that worked thank you so much!!

**Comment by noitcudni** [comment]
@l3luel3l00d I figured out the issue and fixed it in version 2.5. It should be out soon. Probably in a day or so. Can you try it out?

**Comment by l3luel3l00d** [comment]
It is working now, even if two or more browser windows are open

**Comment by noitcudni** [comment]
Coo coo. I don’t think the bug is completed eradicated yet. I will keep
working on it tonight and report back.

**Comment by noitcudni** [comment]
My latest version got rejected by Google, so I'm pretty sure you are still running the version with the same issue.
I've already made the required changes requested by Google. They should approve it. Stay tuned.

**Comment by noitcudni** [comment]
Version 2.5 is out. This shouldn't be a problem anymore. 
@l3luel3l00d I believe that you wrote a review on the web store. Would you reconsider your rating?

Thanks.
