### ISSUE TITLE
Nothing happens after uploading the CSV file

### ISSUE THREAD

**Issue by cristiroma** [noitcudni/google-webmaster-tools-bulk-url-removal#134]
Greetings, I've followed-up the steps from README:
1. Clone the repo and compile the extension
2. Load the extension unpacked in Google Chrome Version 114.0.5735.198 on Linux Mint
3. Run in incognito to run without any extension
4. Visit the Google Search Console page
5. Upload a CSV file

Nothing happens no error in console ... 

https://github.com/noitcudni/google-search-console-bulk-url-removal/assets/634661/963c562e-641e-4ceb-8bbf-1e35e1d83cd6

[Table.csv](https://github.com/noitcudni/google-search-console-bulk-url-removal/files/12038423/Table.csv)

**Comment by noitcudni** [comment]
Is this still a problem. Should be fixed already.
