### ISSUE TITLE
Bulk URL removal extension not working

### ISSUE THREAD

**Issue by AnisMsekni** [noitcudni/google-webmaster-tools-bulk-url-removal#137]
I just purchased the extension and followed all the steps shown in the videos. Simply nothing happens when I add the CSV file. Kindly fix this ASAP.

**Comment by AnisMsekni** [comment]
Fixed.

**Comment by noitcudni** [comment]
Just curious. What was the issue? How did you get it working?

**Comment by AnisMsekni** [comment]
Used private navigation.
