### ISSUE TITLE
bulk-url removal app not working

### ISSUE THREAD

**Issue by Januarycat2013** [noitcudni/google-webmaster-tools-bulk-url-removal#139]
I uploaded the csv file as per the instruction, but it doesn't do anything.

**Comment by noitcudni** [comment]
Can you try reload the page and see if that helps?

**Comment by Januarycat2013** [comment]
No it did't work

**Comment by noitcudni** [comment]
I'm guessing that you installed the version from webstore, correct?

**Comment by Januarycat2013** [comment]
yes

**Comment by Januarycat2013** [comment]
Now it seems to work. I did the first one manually and now it's getting the next ones automatically.

**Comment by noitcudni** [comment]
hmm..strange. I'm going to see if I can reproduce it.

Lih
