### ISSUE TITLE
GSC Bulk Removal Extension 

### ISSUE THREAD

**Issue by Cpointcc** [noitcudni/google-webmaster-tools-bulk-url-removal#140]
I have added the Bulk Removal Extension to my chrome browsers. It says to buy now.  I don't see anywhere that it is a paid tool.  Is this correct?

**Comment by noitcudni** [comment]
That's correct. It has been a paid tool for quite a while now. On Google's chrome webstore, there isn't a "paid" category. The closest one is in-app purchase.
