### ISSUE TITLE
Extension stops randomly

### ISSUE THREAD

**Issue by Ho0tz04** [noitcudni/google-webmaster-tools-bulk-url-removal#144]
I have csv files with anywhere from 50-500 URLs that need to be removed. When I'm using it, it sometimes stops at lower numbers like only processing 3 URLs and sometimes it will process up to 140 in one round. I've been finding the URL it stopped at and editing the csv. I refresh the page, clear the cache, and then restart it. I've been running it in its own browser window where no other tabs are open.

Looking for suggestions. I have run into the quota issue of 1000 URLs but that is a Google thing. I just find the URL it stopped at and repeat the process above the next day. Would love suggestions.

**Comment by noitcudni** [comment]
Can you send me one of the csv files that was giving you problems? I'll see if I can reproduce it. Also, if you can point me to the problematic line(s), that would be great. Email me at lihster.developer@gmail.com

**Comment by Ho0tz04** [comment]
No problem, email sent.

**Comment by cremk** [comment]
I have the same problem as the one stated above. The app stops wirking after remving some urls. My file has 1000 urls and it stops after 10 ro 20 urls and I have to start again to continue

**Comment by noitcudni** [comment]
Please make sure that you don't tab away.You can bring up a
different browser window, however.

**Comment by cremk** [comment]
I have 11000 urls I want to remove.

What strategy should I adopt. Can I remove all of them at once using
the app and then leave it to google to process at its own speed?


<https://constructionreviewonline.com/>

**Comment by noitcudni** [comment]
Google imposes a 1000 limit per 24 hours, so you’d have to do it over 11
days.

**Comment by cremk** [comment]
Thank you for your prompt response.

Can I place a prefix to be removed like this.

http://constructionreviewonline.com/tag/

Or

http://constructionreviewonline.com/de/

To remove all urls associated with any tags and german translated urls
respectively?

**Comment by noitcudni** [comment]
Please refer to
https://github.com/noitcudni/google-search-console-bulk-url-removal?tab=readme-ov-file#csv-format

I also explain the csv format in this video:
https://www.youtube.com/watch?v=F-21eHSxnb8

**Comment by cremk** [comment]
Thanks for this. I now understand
.

Last question I have 11000 pages to remove which will take 11 days.

Problem is that 404 page report on search console does not update the 1000
404 downloadable urls daily (recrawl) for me to be able to download a fresh
list of 1000 pages to remove.

What can I do to get the full list of 11000 404 pages for instance

<https://constructionreviewonline.com/>

**Comment by noitcudni** [comment]
Is it possible to get it from your web server log? Grep for all the 404s.

**Comment by cremk** [comment]
Hi,

I wanted to know if the bulk remover auto news my
subscription monthly since I paid for one month?

Eric
<https://constructionreviewonline.com/>

**Comment by noitcudni** [comment]
Yes, it does.

**Comment by cremk** [comment]
How can I remove autorenew?
<https://constructionreviewonline.com/>

**Comment by noitcudni** [comment]
You can cancel the subscription yourself. I can also do that for you.

**Comment by cremk** [comment]
Please cancel subscription.

<https://constructionreviewonline.com/>

**Comment by noitcudni** [comment]
@cremk, can you email me your email associated with your account? My email is lihster.developer@gmail.com. I'll take care of it.

**Comment by cremk** [comment]
***@***.***
<https://constructionreviewonline.com/>

**Comment by noitcudni** [comment]
@cremik, you can't just reply to the github email. Github strips email addresses. Please email me directly with your email. Thanks.

**Comment by cremk** [comment]
My email address is ***@***.***


<https://constructionreviewonline.com/>
