### ISSUE TITLE
Extension Not working

### ISSUE THREAD

**Issue by anorf1** [noitcudni/google-webmaster-tools-bulk-url-removal#149]
Hey there. I have the latest version of the extension and the upload button does nothing :/

**Comment by noitcudni** [comment]
Just wanted to double check. Are you running this version: [https://chromewebstore.google.com/detail/google-search-console-bul/plcmmfcfbnddbomdlnklhepfkkdmodkf?hl=en](https://chromewebstore.google.com/detail/google-search-console-bul/plcmmfcfbnddbomdlnklhepfkkdmodkf?hl=en)

**Comment by noitcudni** [comment]
As stated in the popup
```
- Go to Google Search Console
- Select the proper domain from the dropdown on the left.
- Select Removals on the left.
- Upload your csv file by clicking on the 'Submit CSV File' button. Check out the example csv below.
```

You have to be on GSC's removal page. Also, you may want to refresh the page once you get there. Email me at lihster.developer@gmail.com if you need further assistance.
