### ISSUE TITLE
tool not working

### ISSUE THREAD

**Issue by NgoiHem** [noitcudni/google-webmaster-tools-bulk-url-removal#151]
![Screenshot 2024-11-06 092636](https://github.com/user-attachments/assets/349e5711-e135-49e1-a586-fb42f06a2d24)
![image](https://github.com/user-attachments/assets/cd5757e0-881a-4cc2-b260-0953fbbe2eec)
I did exactly as the video instructed but the tool still doesn't work. 100% fail

**Comment by NgoiHem** [comment]
of course i'm on the removals page too

**Comment by noitcudni** [comment]
If you click on the download button, you can download the failed urls and it will tell you why them failed. 

In this case, you just need to remove the second column. I made a video on the expected CSV format. Please refer to that.

**Comment by NgoiHem** [comment]
> If you click on the download button, you can download the failed urls and it will tell you why them failed.
> 
> In this case, you just need to remove the second column. I made a video on the expected CSV format. Please refer to that.
![97915350_WINDOWS-106112024_135130](https://github.com/user-attachments/assets/ada6766d-4558-47a4-b925-f047ead76172)
i have downloaded  the failed urls file but it not tell me why them failed. It just url, and not second column, idk why

**Comment by noitcudni** [comment]
As I said, you just need to remove the date column.

**Comment by NgoiHem** [comment]
![97915350_WINDOWS-106112024_14736](https://github.com/user-attachments/assets/8a23fd76-7dc5-4058-8aa2-c6621597e4a7)
like this?

**Comment by noitcudni** [comment]
Yup, you can remove the headers. Without the removal-method column, it will
default to remove-url, so you can drop the second column as well.

**Comment by NgoiHem** [comment]
https://drive.google.com/file/d/1EzEQ4XmdaknEX-7YQXBDUbEEHIgSO_Lj/view?usp=drive_link
it doesn't work

**Comment by noitcudni** [comment]
I will be back in front of my computer in 30 minutes or so. In the
meantime, can you send me your csv file. Email it to
***@***.***

**Comment by NgoiHem** [comment]
![image](https://github.com/user-attachments/assets/30a113ab-7b4b-414e-9dc4-a649225400c3)
i can't see your email. but i can send csv file here:
https://drive.google.com/file/d/1ZqSz2Hlk14tQI82sNn-E3_2A2xOm7ad9/view?usp=sharing

**Comment by NgoiHem** [comment]
oh it's work. idk why it have 1 column date lol. it only shows up when i view in google driver mode.

**Comment by NgoiHem** [comment]
thank you so much for supporting my stupidity xD

**Comment by noitcudni** [comment]
No worries.
