### ISSUE TITLE
413. That’s an error.

### ISSUE THREAD

**Issue by dailybits** [noitcudni/google-webmaster-tools-bulk-url-removal#16]
I'm now getting following error from search console:

"
413. That’s an error.
Your client issued a request that was too large. That’s all we know.
"

**Comment by noitcudni** [comment]
Can you post a screenshot? How can I reproduce it?

**Comment by dailybits** [comment]
I've found the thing.

Mac line break issue, which is causing that all urls are pasted into one big line which gives an overflow.

**Comment by timothythomascoaching** [comment]
I am having this same issue. What did you have to do to correct it?

**Comment by dailybits** [comment]
I had to copy it to Excel and back to a textapp in order to save it with good linebreaks.

**Comment by noitcudni** [comment]
FIXED. It now handles carriage return characters properly.
