### ISSUE TITLE
https://www.google.com/webmasters/tools/removals 

### ISSUE THREAD

**Issue by MacGeyer** [noitcudni/google-webmaster-tools-bulk-url-removal#17]
Hi,

Would it be possible to adapt your script in order to manage https://www.google.com/webmasters/tools/removals submissions ?

**Comment by noitcudni** [comment]
Can you give me a bit more context around your use case? 
Do you find yourself needing this frequently and not just a onetime thing?
What's a typical volume?

**Comment by MacGeyer** [comment]
The submited URLs are mixed with the URLs submited in "Remove URLs"
At this place you can submit URLs for more than just one website but URLs needs to include the domain name.
I already hit the daily 1000 max URLs per day at this place.

**Comment by noitcudni** [comment]
Do you happen to have a list of URLs that I can develop against?

**Comment by noitcudni** [comment]
Please go check out https://github.com/noitcudni/google-webmaster-tools-bulk-outdated-content-removal

**Comment by ano2233** [comment]
what is the exact link where this extension can be used to upload the file ?
there is no link from the readme...
