### ISSUE TITLE
Cant seperate URL's

### ISSUE THREAD

**Issue by Polychemy** [noitcudni/google-webmaster-tools-bulk-url-removal#2]
Hi how do i separate the urls?
i tried this : /n 
in php but it doesn't work. The URLS are not getting sperated.
Also do i export the file in txt format?

**Comment by noitcudni** [comment]
Sorry for the late reply. 

Just put all your urls in a file.

http://foo.com
http://bar.com/foo
...
etc.

It's a straight up csv file, except that it only has one column.
