### ISSUE TITLE
Blanks registering after every row

### ISSUE THREAD

**Issue by leebs23** [noitcudni/google-webmaster-tools-bulk-url-removal#21]
Hi,

I've been using your very helpful tool for several months now without a problem. All of a sudden, I am now getting a blank submission after every row in my CSV file. So the removal tool is attempting to submit a specific URL and then after each one it sees a blank and attempts to do a full Site Removal. It hadn't been happening until just the past few days.

Any idea why this might be occurring and how to resolve?

Thanks!

**Comment by noitcudni** [comment]
Did you pull the latest from master the past few days?  I'm not suggesting that you should. I'm just trying to see if it's a regression I introduced over the weekend.

Can you also send me your CSV file for testing/debugging purposes?

**Comment by leebs23** [comment]
I didn't pull the latest in the past few days as far as I know.

I've attached a very, very simple two-line CSV file that I testing after
thing started going bad over the weekend. This exact format (one URL per
line) has been working fine for months.

Thanks

**Comment by noitcudni** [comment]
Where can I get to your attachment?

**Comment by leebs23** [comment]
Oh. I responded via email and attached, but I guess that doesn't work. Can I email you directly?

**Comment by noitcudni** [comment]
yes. lihster@gmail.com. Thnx.

**Comment by noitcudni** [comment]
This is weird. Maybe the file has an extra newline, but I'm not seeing it in my editors (vim and emacs). 

In any case, I have a fix for it. Please pull from master.

Go to  chrome://extensions and click on the reload button under the bulk url removal tool extension.
Go to Webmaster Tool's Remove URLs page and refresh.
Try your file again.

**Comment by noitcudni** [comment]
![screen shot 2018-10-15 at 2 39 01 pm](https://user-images.githubusercontent.com/78951/46980017-2d5d0280-d088-11e8-94b9-f4db7d7f6827.png)

**Comment by noitcudni** [comment]
Click on the self-referential circle thingy with the arrow.

**Comment by noitcudni** [comment]
https://github.com/noitcudni/google-webmaster-tools-bulk-url-removal/commit/56622158af2ecfc801f994d3e989186586c3b51e
