### ISSUE TITLE
.CSV help

### ISSUE THREAD

**Issue by AngeloTheExplorer** [noitcudni/google-webmaster-tools-bulk-url-removal#22]
What should be inside my .csv file before I request for bulk removal. 

I've tried it and it shows this at the end .html,,,,, at the end of the link. But on the .csv file its not there. 

Thank you so much

**Comment by noitcudni** [comment]
It's basically just a list of urls. For example,
```
http://packershack.com/results/Parra/India
http://packershack.com/results/Pondicherry/India
http://packershack.com/results/Port-Blair/India
http://packershack.com/results/Pune/India
http://packershack.com/results/Puri/India
```
