### ISSUE TITLE
Showing two urls on one line

### ISSUE THREAD

**Issue by serenityenterprises101** [noitcudni/google-webmaster-tools-bulk-url-removal#23]
When I upload urls it is showing 2 on a line. I canceled and did again but still the same is happening. I did with both csv and txt. Do I need to do it again?

**Comment by noitcudni** [comment]
Can you email me your csv/txt file? lihster@gmail.com. Thanks.

**Comment by saifdean93** [comment]
Yes, the same thing happens to me. Does the issue resolve yet?

**Comment by noitcudni** [comment]
@saifdean93,  please email me your csv file. I need to be able to reproduce it in order to debug/fix it.

**Comment by saifdean93** [comment]
@noitcudni I don't think its because of the plugin, the same thing happens if I didn't use the plugin. The problem is the link turns to this; _**http:///website.com/http:///website.com/somethinghere.htm**_ so i 
 figure out by removing the http in the list, so it will become like this _**/somethinghere.htm**_ . And it works.

**Comment by serenityenterprises101** [comment]
Delete the https://mywebsite.com and just add the ending for example
/mypage2   and not https://mywebsite.com/mypage2.

Thats what worked for me.
Blessings,Rhonda JonesPlease Like My Fan Page The Christian Meditation Website
The Secret Place Yoga & MeditationGetaway with God Retreats 

    On Monday, March 4, 2019, 8:18:17 PM PST, saifdean93 <notifications@github.com> wrote:  
 
 
@noitcudni I don't think its because of the plugin, the same thing happens if I didn't use the plugin. The problem is the link turns to this; http:///website.com/http:///website.com/somethinghere.htm so i
figure out by removing the http in the list, so it will become like this /somethinghere.htm . And it works.
