### ISSUE TITLE
link where extension can be used to upload file

### ISSUE THREAD

**Issue by ano2233** [noitcudni/google-webmaster-tools-bulk-url-removal#24]
what is the exact link where this extension can be used to upload the file ?
there is no link from the readme...

**Comment by noitcudni** [comment]
You have to go to the old webmaster tools and visit the page where you
normally remove url. You should be able to find a new button there.

**Comment by ano2233** [comment]
i only normally remove through the 'outdated content ' page. i have never removed through the webmaster/index/remove page like you said.... please read the my emails...

**Comment by noitcudni** [comment]
Installed the wrong extension. Closing this issue.
