### ISSUE TITLE
New search console question

### ISSUE THREAD

**Issue by jammersdublin** [noitcudni/google-webmaster-tools-bulk-url-removal#25]
I know that the new search console has a different interface, is the removals section hidden in there? I can still access the old site, and use this tool, but wondering if this extension will support the new style one?

**Comment by noitcudni** [comment]
I couldn't find the removal section in their new version last time (around xmas) I checked. Please let me know if you find it. I'm guessing that they're still porting the old features over.

**Comment by turk** [comment]
> I couldn't find the removal section in their new version last time (around xmas) I checked. Please let me know if you find it. I'm guessing that they're still porting the old features over.

Could you check here - https://www.google.com/webmasters/tools/removals?pli=1 - ?

**Comment by noitcudni** [comment]
I wrote another extension of that: https://github.com/noitcudni/google-webmaster-tools-bulk-outdated-content-removal.
