### ISSUE TITLE
Reporting a bug

### ISSUE THREAD

**Issue by ghost** [noitcudni/google-webmaster-tools-bulk-url-removal#27]
Hi,

There is a bug. Because Google Removal Outdated Content tool is old and probably not very well updated and integrated with the other systems, sometimes it will force local language despite IP, OS settings, Chrome settings, Google Account settings and preferences, clearing the cache and logging in and logging out. All other services would be in English from the modern ones that are maintained, but not that one. That way, when you load the URL https://www.google.com/webmasters/tools/removals it will always show local language. I did had that issue before and I found a special hack to add ?hl=en to the URL, which will force the English version and then your button will appear.

I would consider telling people they have to add ?hl=en and/or adding languages to your tool to fix that. Maybe it is the size of the button in other languages or something else that is not helping your button to appear. Not sure.

Again, that is an issue with the Google service as it doesn't respect any settings as it is outdated. I think you need to address your tool, I've seen feedback that it doesn't work and I believe it is for that reason.

**Comment by noitcudni** [comment]
Thanks for your bug reporting. Just wanted to double check. This bug should be assigned to https://github.com/noitcudni/google-webmaster-tools-bulk-outdated-content-removal, right? 

I'll fix it this weekend.

**Comment by noitcudni** [comment]
Didn't get around to fixing it for good, but I did take a quick look to see why the button isn't showing up for languages other than English. I'm expecting a button with `Request Removal` to be there. I'll put in a dialog with an appropriate message. Thanks again for the bug report.
