### ISSUE TITLE
Error to install this extension

### ISSUE THREAD

**Issue by raju0092** [noitcudni/google-webmaster-tools-bulk-url-removal#30]
Not installed this extension please update latest version

Show error message is:-
Manifest file is missing or unreadable
Could not load manifest.

**Comment by noitcudni** [comment]
Still need help with this?

**Comment by markovic-mr** [comment]
I need help...Chrome is throwing errors regarding missing files
I point it to google-webmaster-tools-bulk-url-removal-master\resources\unpacked so it finds manifest file, but then it refers to missing image. I copy the images folder from "shared" so image is found, but then I get another error "Could not load JavaScript 'compiled/content-script/main.js' for content script."
I cannot find this file in the package, so please help...

**Comment by noitcudni** [comment]
Did you follow the instructions in the readme to compile clojurescript to
JavaScript?

**Comment by markovic-mr** [comment]
I'm a windows user, I have trouble installing lein..

**Comment by noitcudni** [comment]
https://djpowell.github.io/leiningen-win-installer/

Try the instructions from here.

**Comment by markovic-mr** [comment]
OK, so I have successfully installed Java jdk-12.0.2_windows-x64_bin.
But Lein windows installer is not recognising the Java installation and cannot install Lein..
And when I try to run "lein.bat" from cmd, I get an error:
'"java"' is not recognized as an internal or external command,
operable program or batch file.

**Comment by markovic-mr** [comment]
Should I try to find JAVA SE 7? It's not available for download on official https://www.oracle.com/technetwork/java/javase/downloads/index.html

**Comment by noitcudni** [comment]
You'll need to make sure that Java is in your path.

**Comment by markovic-mr** [comment]
it's in C:\Program Files\Java\jdk-12.0.2

**Comment by noitcudni** [comment]
Great, you will need to make sure that java is in your PATH. https://stackoverflow.com/questions/1672281/environment-variables-for-java-installation.

In other words, in your cmd prompt you should be able to type java.

**Comment by markovic-mr** [comment]
Got it. I can type java in cmd.
After running lein.bat, I got no error.
So I 'cd' into the google-webmaster-tools-bulk-url-removal-master and typed len release && lein package
Got an error:
C:\Users\GetToNet\Downloads\google-webmaster-tools-bulk-url-removal-master>len release && lein package
'len' is not recognized as an internal or external command,
operable program or batch file.

**Comment by noitcudni** [comment]
Similar issue here. You'll need to include lein as part of your PATH.

**Comment by markovic-mr** [comment]
...or put lein.bat in the project folder....looks like it's working & compiling now...

**Comment by markovic-mr** [comment]
Thank you, you have been very helpful!

**Comment by noitcudni** [comment]
I'm glad that it works for you.
