### ISSUE TITLE
The tool get stuck after "A removal request for this URL has already been made." error

### ISSUE THREAD

**Issue by quangtn** [noitcudni/google-webmaster-tools-bulk-url-removal#31]
When I get the warning "A removal request for this URL has already been made.", the input batch process is stopped and doesn't move to next url when i click Continue button. Is there a way to fix this?

**Comment by quangtn** [comment]
To add more info, the page reloads, but it doesn't seem to move on the next url as I keep clicking the Continue button

**Comment by noitcudni** [comment]
Ah yes. I failed to capture the case you brought up. I will work on it tomorrow. Thanks for bringing it up to my attention

**Comment by quangtn** [comment]
Thanks!

**Comment by noitcudni** [comment]
So, I have a fix for this. Unfortunately, I can't really test it until google gets around to remove my url.

**Comment by quangtn** [comment]
Oh, do you have any time estimate based on last update. e.g How long does it take for Google to update your code.

Is this something I can manually update on my end?

**Comment by noitcudni** [comment]
My previous comment is not about google updating my code. I was more concerned with when google actually gets around to remove my test URL, so I can test my changes. 

Google finally got around to remove my URL. So, I tried submitted it again without the extension, fully expecting that I'll trigger the aforementioned error message. However, it happily took on the same URL.

Now I'm a bit confused. How do I trigger the "A removal request for this URL has already been made."?

**Comment by noitcudni** [comment]
To answer your question. Once I can reproduce the error message, I can test my changes. Pushing to github and updating the extension on Google Web store are almost instantaneous.

**Comment by noitcudni** [comment]
Also, a screenshot may help as well.

**Comment by quangtn** [comment]
I just tried it again. This time it redirect back with empty file input that I will need to upload again. Here's the screenshot.
![CaptureGTM](https://user-images.githubusercontent.com/1731721/64054466-f8d92480-cb3b-11e9-9605-35efb6fffcdb.JPG)

**Comment by noitcudni** [comment]
email me directly at lihster@gmail.com

**Comment by noitcudni** [comment]
FIXED. Closing ticket.
