### ISSUE TITLE
One click processing?

### ISSUE THREAD

**Issue by aeternaldreams** [noitcudni/google-webmaster-tools-bulk-url-removal#33]
Hey,
Just purchased this extension and have my work cut out for me trying to remove several thousand pharma spam urls. I have my CSV file saved with about 1000 URLs to start with, however, after submitting the file I need to manually hit continue each time to process subsequent URLS.

I get this error in developer's console:

Uncaught TypeError: Cannot read property 'b' of null
    at Object.setBubbleVisible (4227820770-wmx__en.js:561)
    at window.scLinkBubble (removals-request?hl=en&siteUrl=[Redacted])
    at <anonymous>:1:23

as well as this warning: 

[Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2

I tried running the script in both my normal chrome window as well as an incognito window with limited extensions loaded (in case of a conflict). Appreciate any help.

**Comment by noitcudni** [comment]
Can you send me your csv file?

**Comment by noitcudni** [comment]
Thanks for sending me the csv file. I was able to reproduce the bug. Apparently, I wasn't handling spaces in URLs correctly. Version 0.11 should fix it.

**Comment by aeternaldreams** [comment]
Thank you! It's working great now. I appreciate the quick response.
