### ISSUE TITLE
You have reached your submission limit. Please try again later 

### ISSUE THREAD

**Issue by brahmm9640** [noitcudni/google-webmaster-tools-bulk-url-removal#34]
getting below error in search console Remove URLs 
You have reached your submission limit. Please try again later 

can you help me in that

**Comment by noitcudni** [comment]
The extension should pause and show a continue button.  You'll need to wait
awhile and click on continue. Let me know if that doesn't work.

**Comment by brahmm9640** [comment]
i tried , but not working

**Comment by noitcudni** [comment]
How long did you wait? Also, can you provide a screenshot.

**Comment by noitcudni** [comment]
Did you try again? If it's not working, please provide me with more information in terms of what you are seeing. URLs got messed up. It tried but didn't progress. How many URLs are you trying to remove? You can also send me your csv file

**Comment by roland71** [comment]
Same here, clicking continue has no effect. Removed a lot of urls over different properties. Maybe 200 each property. How long do I have to wait? Thanks!

**Comment by noitcudni** [comment]
If the top of the page says the same error message, that means the Google
is still throttling.

**Comment by noitcudni** [comment]
I don't know how long Google wants you to wait.
