### ISSUE TITLE
WebMaster Tools - Bulk URL removal - Error 

### ISSUE THREAD

**Issue by fervic23** [noitcudni/google-webmaster-tools-bulk-url-removal#36]
Hi,

I'm receiving an error everytime I try to purchase the extension on Chrome Web store. Is there an issue right now?

error message:An unexpected error has occurred. Please try again later. [OR-CAC-20]

**Comment by noitcudni** [comment]
Can you attach a screenshot? I don't own the purchasing flow. It's most
likely a google issue.

**Comment by fervic23** [comment]
<img width="1884" alt="Screen Shot 2019-10-14 at 7 53 37 AM" src="https://user-images.githubusercontent.com/56422619/66724363-cf5c2a00-ee57-11e9-9c8c-7fdfc50aa844.png">

Hi,

This is what I get everytime I try to purchase the extension. Thanks!

**Comment by noitcudni** [comment]
Hmm, other purchases have been coming through. Maybe try using a different
account?

**Comment by fervic23** [comment]
This is noted. Will try to do that

**Comment by fervic23** [comment]
Hi!

I was able to make the purchase and go through the process of uploading the CSV file but I always landed back to this error page.

<img width="1911" alt="Screen Shot 2019-10-14 at 10 11 38 AM" src="https://user-images.githubusercontent.com/56422619/66726342-6088cc00-ee6b-11e9-8760-64a5f11b2970.png">

Am I doing anything wrong? The URL on the file is 26k Is there some kind of limit? Thanks!

**Comment by noitcudni** [comment]
There's no specific limit. What's your language setting? Also, feel free to
send me your csv file.

Did it process some prior to getting Error 500?

Lih

**Comment by fervic23** [comment]
Yes. It did process some then it gives the error 500. 

Here's the CSV file, settings is on English.

Which email should I send the CSV file to?

**Comment by noitcudni** [comment]
lihster@gmail.com

**Comment by noitcudni** [comment]
Spoke on skype. Closing
