### ISSUE TITLE
he comprado la extension y no sale donde poner el archivo csv

### ISSUE THREAD

**Issue by manuel1974** [noitcudni/google-webmaster-tools-bulk-url-removal#39]
tengo instalado la extension de chrome que he comprado en la strore.
en principio me sale el icono en la pagina de chrome en verde pero cuando voy a la herramienta de eliminacion de google no me aparece el recuadro donde puedo poner el archivo csv
![eliminar url](https://user-images.githubusercontent.com/53948909/68466499-d2f38e80-0214-11ea-87b2-e645a3b9756f.png)

**Comment by manuel1974** [comment]
estoy haciendolo manualmente y es un trabajo de chinos

**Comment by noitcudni** [comment]
First of all, you installed the wrong extension. It's
google-webmaster-tools-bulk-outdated-content-removal that you want.
Second, you will need to switch your language settings to English.
Third, I'm the Chino who wrote these extensions, so show some respect.

**Comment by shendison** [comment]
Perfect response!

**Comment by manuel1974** [comment]
creo que teneis un problema de traduccion
la expresion trabajo de chino significa trabajo lento y [dificil.](url)
No tiene nada de ataque  ni falta de respeto como me quereis hacer ver.
Solo tengo que eliminar 1000 url a mano y es un trabajo para el que queria esta herramienta.

**Comment by noitcudni** [comment]
From your screenshot, this is what you want: https://github.com/noitcudni/google-webmaster-tools-bulk-outdated-content-removal.

Also, it will only work if your language settings is set to English, unfortunately.
