### ISSUE TITLE
Link to "How to Extract a List of All URLs Indexed by Google for Your Website" is dead.

### ISSUE THREAD

**Issue by aartek** [noitcudni/google-webmaster-tools-bulk-url-removal#4]
"How to Extract a List of All URLs Indexed by Google for Your Website" link in description is dead, so I suggest to replace it with another one.

For example, there is a link for working bookmarklet to retrieve urls of google:
http://www.onlinesales.co.uk/tools/tools/bookmarklet-serps.php
(Bookmarklet code [mirror1](http://hastebin.com/lotiwiduje.apache) and [mirror2](http://pastebin.com/AhKFV4xN))

Instruction:
1. Type `site:[your site url]` e.g. `site:reddit.com` in http://google.com
2. Click bookmarklet
3. Copy links to text file and save

BTW Thanks for this tool. It saved me a lot of work!

**Comment by ppezier** [comment]
Original instructions can also be found with [Wayback Machine](https://web.archive.org/web/20160101151813/https://www.highposition.com/blog/how-to-extract-list-urls-indexed-by-google-for-your-website/).

**Comment by mindbreaker** [comment]
#12 Made an pull request for update.
