### ISSUE TITLE
Manifest file error

### ISSUE THREAD

**Issue by Enzyme420** [noitcudni/google-webmaster-tools-bulk-url-removal#40]
I installed java and leiningen and compiled the file but when i try to unpack the file in the browser chrome etccc i get the manisfest file error can anyone please tell me what i  did wrong i followed the instructions thouroughly and i can't seem to find the solution p.s i did enable developer mode

**Comment by achpa** [comment]
> I installed java and leiningen and compiled the file but when i try to unpack the file in the browser chrome etccc i get the manisfest file error can anyone please tell me what i did wrong i followed the instructions thouroughly and i can't seem to find the solution p.s i did enable developer mode

same issue

**Comment by Enzyme420** [comment]
> > I installed java and leiningen and compiled the file but when i try to unpack the file in the browser chrome etccc i get the manisfest file error can anyone please tell me what i did wrong i followed the instructions thouroughly and i can't seem to find the solution p.s i did enable developer mode
> 
> same issue

Hi mate i know it's really annoying at first i thought it was because i was using windows since the .sh files are for linux platforms so then i installed kali linux on a virtual machine and everything seemed to work fine jave leiningen etc but when it came to adding the extension on the browser it gave me the annoying error sorry to hear you are having the same issue if i find a solution i will leave a comment with the fix don't think it will be anytime soon though cause i'm super busy lately infact needed the extension to save some time but anyways... :'D
