### ISSUE TITLE
Internal Server Error Error 500

### ISSUE THREAD

**Issue by plotino** [noitcudni/google-webmaster-tools-bulk-url-removal#43]
error search console--> Internal Server Error Error 500

**Comment by noitcudni** [comment]
It's because you have invalid urls in.your CSV file. Please send me your
CSV file, and I'll take a look.

**Comment by samuel840** [comment]
I have the same issue as well. I bought your extension and cant remove now.
enclosed is the xlsx format of the urls to be removed
[remove.xlsx](https://github.com/noitcudni/google-webmaster-tools-bulk-url-removal/files/3941495/remove.xlsx)

**Comment by noitcudni** [comment]
Please convert your xlsx file into csv format.

**Comment by plotino** [comment]
[https___eidosdesarrolloweb.com_ Index Coverage Drilldown 2019-12-10.csv.zip](https://github.com/noitcudni/google-webmaster-tools-bulk-url-removal/files/3946088/https___eidosdesarrolloweb.com_.Index.Coverage.Drilldown.2019-12-10.csv.zip)

**Comment by noitcudni** [comment]
Thanks for the file.  A few things I would like to point out.
1. Get rid of the header, ie. `URL,Último rastreo`.
2. I'm not sure why you have dates in the second column.  Remove that column.

**Comment by noitcudni** [comment]
[output.txt](https://github.com/noitcudni/google-webmaster-tools-bulk-url-removal/files/3946944/output.txt)

^^^ Please try this file out.

**Comment by plotino** [comment]
With your file I get the same error:  Internal Server Error
Error 500

**Comment by noitcudni** [comment]
Did some of them go through? I just did a quick sample of 5 urls from your file, and they went fine.

**Comment by plotino** [comment]
Hi!! I think I did not take any url, it gives an error 500 directly :(

**Comment by noitcudni** [comment]
Hmm..if you're ok with it, add me to your google webmaster tools, I will
try to do it on my end. By glancing at the file, it should work. If you
decided to add me to your account temporarily, my email address is
lihster.developer@gmail.com

**Comment by plotino** [comment]
Ok you already have it

**Comment by noitcudni** [comment]
Got it. Thanks. It's running right now. Seems to be working fine.

I believe the problem was that you didn't click on the "clear local
storage" button, so it was probably resubmitting broken urls again.

**Comment by plotino** [comment]
Hi, that's perfect I try it and I tell you

**Comment by noitcudni** [comment]
@plotino I'd like to close this issue if it's working for you.
