### ISSUE TITLE
With the new version, is does not make automatic

### ISSUE THREAD

**Issue by davidperezgar** [noitcudni/google-webmaster-tools-bulk-url-removal#44]
Hello, I have to push Send to every url in order to make the bulk removal. Before it was everything atuomatic. Do you know where is the problem?

**Comment by noitcudni** [comment]
Send me your csv file. I will take a look at it. Which version are
you using?

**Comment by noitcudni** [comment]
Yup, I did introduce a bug in the later version. My apologies. I'm fixing it now.

**Comment by noitcudni** [comment]
duplicate issue: https://github.com/noitcudni/google-webmaster-tools-bulk-url-removal/issues/45
