### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by thorranthe** [noitcudni/google-webmaster-tools-bulk-url-removal#48]
Hi
I just purchased the extension and get "Internal Server Error 500" every time I try to run it. I'm running the Crome 79.0.3945.117 on MacOS Catalina. Any idea what the problem is? I really need this one!

**Comment by noitcudni** [comment]
Please take a look at your csv file. The second column of present should be
the removal method. See readme for more info.

Also, you can send me your csv file.

**Comment by thorranthe** [comment]
Thanks a lot for fast reply!

I only have 2 columns. First is "URL" and second is the "Last crawled". I get the list from the Coverage section of Google Search Console.

CSV file have been send to you email...

**Comment by thorranthe** [comment]
My apologies. I did not read the readme probably. Things are working now - thanks!
