### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by ricardogonzalezcari** [noitcudni/google-webmaster-tools-bulk-url-removal#49]
Hello Everybody, i follow the instructions, but when i uploaded the .CSV file i get and Internar Server Error 500.

Is this something momentary or anything else?

I will appreciate your support.
Regards.

**Comment by noitcudni** [comment]
Hi,
The second column (optional) in the CSV file denotes the removal method. That mostly likely means that the removal method is invalid, ie. not PAGE,  nor PAGE_CACHE, nor DIRECTORY.  Refer to README for more info.

Did it work for a bit and then 500? 

To answer your question, this is not something momentary, but fixing the csv file should fix the problem.

Please send me your CSV file.
