### ISSUE TITLE
Google Changing Interface for URL Removal

### ISSUE THREAD

**Issue by advancedperiodontics** [noitcudni/google-webmaster-tools-bulk-url-removal#50]
![image](https://user-images.githubusercontent.com/32933521/73273518-1e815d00-41b2-11ea-9285-af8a92518339.png)

**Comment by noitcudni** [comment]
Thank you so much for bringing that to my attention. Will start working on it.

**Comment by dariuserdt** [comment]
Are you going to update the chrome extension as well for the new removals report?

**Comment by noitcudni** [comment]
Yes, that's the plan. You can follow my progress here: https://github.com/noitcudni/google-webmaster-tools-bulk-url-removal/tree/new-search-console

**Comment by noitcudni** [comment]
The latest release works with the new Google Search Console interface.

**Comment by advancedperiodontics** [comment]
After clicking "Submit CSV File", for me nothing happens.  I've tried my CSV format with URLs only, as well as with the two additional fields 'removal-method' and 'url-type'.  Should I create a new issue?

**Comment by noitcudni** [comment]
What's the url showing in your browser? Send me a screenshot of your entire browser window. 

Sure, file a new issue to track this.

**Comment by advancedperiodontics** [comment]
Hello, I had previously purchased both of your applications on the chrome
webstore.  It's now asking me for a gumroad license key.  Can I get my
access restored from my previous purchases?
Max Druiz

*Marketing ManagerAdvanced Periodontics & Implant Dentistry*
973-718-5190 <9737185190>

**Comment by noitcudni** [comment]
Please email me directly at ***@***.***, and I'll take care
of it.
