### ISSUE TITLE
Chrome extension often pauses the process

### ISSUE THREAD

**Issue by dariuserdt** [noitcudni/google-webmaster-tools-bulk-url-removal#51]
Hi there, I really like your chrome extension. However, I have the impression that it does not work as good as in the past. The tool often paused and I manually have to click on "submit" that the process continues. Do you have ideas what is the reason behind that?

**Comment by noitcudni** [comment]
I have a new version that's currently being reviewed. It will skip over problematic entries. At the end of the run, you can download the skipped entries.

In the meantime, feel free to send me your csv file. I'll take a look.

**Comment by dariuserdt** [comment]
Sounds good. I'm happy to also have this extension working for the new
removal tool.

Regarding why it sometimes paused: Maybe it is because of conflicts with
other chrome addons. I have to check that out..

Lih <notifications@github.com> schrieb am Mo., 3. Feb. 2020, 18:14:

**Comment by noitcudni** [comment]
I don't think that's why. The version that you were using long time ago simply skipped over urls that it couldn't handle without any user feedback. If you send me your csv file, I can try reproduce the problem later tonight on my end.

**Comment by dariuserdt** [comment]
But if I then click to submit, it can handle it. So it does not seem to be
a URL data problem. It is not the same as if I entered a wrong URL (not
suiting property) or a duplicated URL. I would say this issue started in
November or December 2019..

I don't have a list to check for you now. But I would say I wait for the
new deployment and then we see how it goes.


Lih <notifications@github.com> schrieb am Mo., 3. Feb. 2020, 18:45:

**Comment by noitcudni** [comment]
I don't know how long you are going to wait 'cause its status has been
under review for more than a week now.  It's up to you. If you have a list
of URLs that's causing that pause problem, send it my way, and I can look
into it.

Lih
