### ISSUE TITLE
Add to Chrome button is not working

### ISSUE THREAD

**Issue by Kaps1112** [noitcudni/google-webmaster-tools-bulk-url-removal#52]
Hi,
I have purchased the plugin however after purchasing the 'Add to Chrome' button isn't responding after clicking on it.

Please help ASAP.

Order No. is CWS.0500-8758-7608-00708

**Comment by noitcudni** [comment]
Weird.. if you go directly to the legacy url removal page, do you see the
extra
buttons?

**Comment by Kaps1112** [comment]
Nope :(

**Comment by noitcudni** [comment]
Unfortunately, I have no control over that button. Maybe try clearing your
cache?

**Comment by noitcudni** [comment]
Did this get resolved? If not, email me directly. I'll address this later tonight.

**Comment by Kaps1112** [comment]
Hi Lih,
Nope. Not yet ☹

**Comment by noitcudni** [comment]
Please email me your email directly. lihster.developer@gmail.com

**Comment by noitcudni** [comment]
Resolved via email.
