### ISSUE TITLE
Download Failed - Forbidden

### ISSUE THREAD

**Issue by michelelang** [noitcudni/google-webmaster-tools-bulk-url-removal#53]
Hello, 

I just purchased this and when it started to download it said 'failed - forbidden' (please see in attached screenshot).

![Screen Shot 2020-02-12 at 11 34 42 AM](https://user-images.githubusercontent.com/34300727/74370389-e4a47f00-4d8b-11ea-8f80-c5a8ac6f06b7.png)

**Comment by noitcudni** [comment]
Did this get resolved?

**Comment by michelelang** [comment]
yes thank you! When will the tool be compatible for the new search console?
