### ISSUE TITLE
New Search Console 

### ISSUE THREAD

**Issue by michelelang** [noitcudni/google-webmaster-tools-bulk-url-removal#54]
When will the tool be available for the new search console? If it is not soon, I will need to cancel and get a refund. I am unable to use the legacy tool.

**Comment by noitcudni** [comment]
It will be ready before 2/27. I was working on it this weekend and got most
of it working. There is a couple more things I'll need to do to wrap it all
up.

**Comment by noitcudni** [comment]
Why can't you use the legacy tool? What problems are you having?

**Comment by michelelang** [comment]
Okay thank you. Only one of my verified domains shows under the legacy console, and when I try to access my other verified domain (which I need the bulk removal tool for) it switches me to the new tool. In Legacy, when I add the needed domain to the url parameter it tells me that I am not verified. So I can only access the domain that I need the tool for on the new search console.

**Comment by dfa457** [comment]
Just paid for the tool but unable to use it in the new search console. Old search console is gone and this tool doesn´t work for the new one. Why you still sell it?....totally dissapointed! Wasted money

**Comment by MrZANO** [comment]
I'm waiting for the new release! 👍 Many Thanks

**Comment by MrZANO** [comment]
> Just paid for the tool but unable to use it in the new search console. Old search console is gone and this tool doesn´t work for the new one. Why you still sell it?....totally dissapointed! Wasted money

https://www.google.com/webmasters/tools/url-removal for now works

**Comment by noitcudni** [comment]
> Just paid for the tool but unable to use it in the new search console. Old search console is gone and this tool doesn´t work for the new one. Why you still sell it?....totally dissapointed! Wasted money

As stated in the description of the extension on Chrome webstore and again in the github project's readme
```
ATTENTION: THIS EXTENSION CURRENTLY WORKS WITH THE LEGACY VERSION ONLY. YOU CAN GET TO THE OLD VERSION HERE:  https://www.google.com/webmasters/tools/url-removal.  
I'm currently in the process of porting it over to work with the new search console.
```

@dfa457 Let me know if you still have problems getting it to work.

**Comment by noitcudni** [comment]
Just submitted a version that works with the new search console on Chrome Web Store. Pending approval.

**Comment by michelelang** [comment]
Great! Thank you for the update!

**Comment by dfa457** [comment]
> > Just paid for the tool but unable to use it in the new search console. Old search console is gone and this tool doesn´t work for the new one. Why you still sell it?....totally dissapointed! Wasted money
> 
> https://www.google.com/webmasters/tools/url-removal for now works

You´re right! It´s working on the old search console. I couldn´t find the root to that version until now.

**Comment by noitcudni** [comment]
The version that works with the new Google Search Console has gotten approved and is now available on the webstore.

**Comment by michelelang** [comment]
Great! Can you please send the link? Do I have to re-purchase? If so, I would like a refund for the old version since I did not use it. 

Thank you

**Comment by michelelang** [comment]
![Screen Shot 2020-02-19 at 8 57 15 AM](https://user-images.githubusercontent.com/34300727/74855707-e7f0bb00-52f5-11ea-9b60-b92d3c4a2010.png)

It is not letting me upload a new file - this is the old file that I uploaded and canceled.

**Comment by michelelang** [comment]
Great! I am having trouble getting it to work. I updated the extension. Now when I try to submit my csv file, it lets me search for the file and add, but then nothing happens.
![Screen Shot 2020-02-19 at 9 15 59 AM](https://user-images.githubusercontent.com/34300727/74857449-8b42cf80-52f8-11ea-88ce-434e31183cd7.png)

**Comment by noitcudni** [comment]
hmm..I will try it on my end later tonight. Can you go into your developer console and click on view cache and send that to me. Also, can you send me your csv file?

**Comment by michelelang** [comment]
![Screen Shot 2020-02-19 at 10 22 45 AM](https://user-images.githubusercontent.com/34300727/74863640-0e692300-5303-11ea-8b93-eefca59afe08.png)


Thank you!

Please find attached screenshot of developer console and csv file. When I click 'view cache' while I am in the developer console, nothing happens.

**Comment by noitcudni** [comment]
can you email me your csv file as well?

**Comment by michelelang** [comment]
Attached here, is it not showing?

**Comment by noitcudni** [comment]
No, just email it to me at lihster.developer.com.

**Comment by michelelang** [comment]
It is not lihster@developer.com <mailto:lihster@developer.com>?

**Comment by noitcudni** [comment]
lihster.developer@gmail.com

**Comment by noitcudni** [comment]
Ah..I see. I specified my extension to work exclusively on `https://search.google.com/u/1/search-console/removals*`, but it appears that the u/1/ might change to u/2/. 

What url is your browser showing in the url bar?

**Comment by noitcudni** [comment]
Ah I see. The integer in the `https://search.google.com/u/[integer]/search-console maps to which a particular google account logged in on the browser. 

So, I have lihster@gmail.com and lihster.developer@gmail.com
lihster@gmail.com is mapped to `0` while lihster.developer@gmail.com is mapped to `1`. 

OK, I'll need to patch this one up.

**Comment by noitcudni** [comment]
@michelelang  I just submitted a new release. It's waiting on Google Webstore's approval.  

If you don't want to wait, a work around is to first log out from your google account on your chrome browser via gmail. Log in with a separate account as a placeholder (it will be mapped to 0). Then, log in again with the account that's the owner of the domain.

In other orders.
https://search.google.com/u/0/search-console --> [some account]
https://search.google.com/u/1/search-console --> [the real account. Presumably, the one you are using right now]

Sorry about the inconvenience.

**Comment by josepbbs** [comment]
Hi,
We have a problem, we are not able to see the "Submit CSV file" button in the removal section
https://search.google.com/search-console/not-verified?original_url=/search-console/removals&original_resource_id

we changed the languaje default setting to english and still not working
any ideas please?

**Comment by noitcudni** [comment]
Need to run an errand. Will get back in to you in a couple hours. In the
meantime, can you take a screenshot and send me your csv file.

**Comment by noitcudni** [comment]
@josepbbs, you'll need to select a "property" on the left-hand pane. Also, the "Submit CSV file" button is inside the extension popup. You need to click on the green trash can icon.

**Comment by josepbbs** [comment]
> @josepbbs, you'll need to select a "property" on the left-hand pane. Also, the "Submit CSV file" button is inside the extension popup. You need to click on the green trash can icon.

thanks for your answer @noitcudni 
I managed to see the green trash icon, it had disabled itself due to unknow reason
now the problem is that when I clock on the removal link on the left panel it shows this strange error

> _500. That’s an error.
> 
> There was an error. Please try again later. That’s all we know._

tested on chrome and firefox browser and selecting the right property...

does somebody have this error too?

any ideas?

**Comment by CBaum99** [comment]
Hi,
for me as well nothing happens after submiting the CSV - using 
https://search.google.com/search-console/removals?resource_id=sc-domain%3AxxxDOMAINxxx&hl=en

**Comment by noitcudni** [comment]
> > @josepbbs, you'll need to select a "property" on the left-hand pane. Also, the "Submit CSV file" button is inside the extension popup. You need to click on the green trash can icon.
> 
> thanks for your answer @noitcudni
> I managed to see the green trash icon, it had disabled itself due to unknow reason
> now the problem is that when I clock on the removal link on the left panel it shows this strange error
> 
> > _500. That’s an error.
> > There was an error. Please try again later. That’s all we know._
> 
> tested on chrome and firefox browser and selecting the right property...
> 
> does somebody have this error too?
> 
> any ideas?
