### ISSUE TITLE
500 when clicking on the removal tab

### ISSUE THREAD

**Issue by noitcudni** [noitcudni/google-webmaster-tools-bulk-url-removal#56]
> @josepbbs, you'll need to select a "property" on the left-hand pane. Also, the "Submit CSV file" button is inside the extension popup. You need to click on the green trash can icon.

thanks for your answer @noitcudni 
I managed to see the green trash icon, it had disabled itself due to unknow reason
now the problem is that when I clock on the removal link on the left panel it shows this strange error

> _500. That’s an error.
> 
> There was an error. Please try again later. That’s all we know._

tested on chrome and firefox browser and selecting the right property...

does somebody have this error too?

any ideas?

_Originally posted by @josepbbs in https://github.com/noitcudni/google-search-console-bulk-url-removal/issues/54#issuecomment-591092954_

**Comment by noitcudni** [comment]
@josepbbs, let's track it here.

**Comment by noitcudni** [comment]
That's strange. Can you send me a screenshot? The 500 error is coming from the search console's server.

**Comment by josepbbs** [comment]
yes , attached

![Captura de pantalla 2020-02-26 22 56 49](https://user-images.githubusercontent.com/59019740/75391950-5da6e900-58eb-11ea-8378-457bdccb65a9.png)

**Comment by josepbbs** [comment]
this happens when doing cick in removals

![Captura de pantalla 2020-02-26 22 58 49](https://user-images.githubusercontent.com/59019740/75392073-9646c280-58eb-11ea-8a59-0342e9fa24a8.png)

**Comment by noitcudni** [comment]
Can you deactivate my extension for the moment and see if the problem you are experiencing persists? I just wanted to make sure that it's not my extension that's causing the problem.

**Comment by noitcudni** [comment]
Also, what happens when you hit refresh after you got the 500 error page?

**Comment by josepbbs** [comment]
I disabled the extension and it still persists the problem,
So I'm afraid this problem comes from other way
I willl have to try in other computer

**Comment by noitcudni** [comment]
Can also try clearing your browser cache.

**Comment by josepbbs** [comment]
I cleared browser cache, I tried in Mac OS and in Windows different computers, chrome and firefox
I think it's not your extension, the error comes from other way , it's much strange, I am not able to get the removals section and it gives always error 500

Anybody had this error too?

**Comment by josepbbs** [comment]
Today the remolvals section started aparently to work normally without doing anything else special
Don't know what might have happened, but I hope it keeps working normally, so you can close the topic at the moment
thanks
