### ISSUE TITLE
Nothing happens after submitting the CSV file

### ISSUE THREAD

**Issue by noitcudni** [noitcudni/google-webmaster-tools-bulk-url-removal#57]
Hi,
for me as well nothing happens after submiting the CSV - using 
https://search.google.com/search-console/removals?resource_id=sc-domain%3AxxxDOMAINxxx&hl=en

_Originally posted by @CBaum99 in https://github.com/noitcudni/google-search-console-bulk-url-removal/issues/54#issuecomment-591371869_

**Comment by noitcudni** [comment]
@CBaum99, let's track it here.

**Comment by noitcudni** [comment]
Is your language setting in English?

**Comment by noitcudni** [comment]
Try refresh the page. 
Did the trash can show a number with a red icon after a run?
Can you send me your CSV file?

**Comment by noitcudni** [comment]
Ah, interesting.

Yes, I am able to reproduce this weird bug. 
When I first visited search.google.com/.... and tried submitting my csv file, nothing happened.  Then, I refreshed the page, and it proceeded to work. 

I need to fix that obviously. In the meantime, the work around is to refresh the page first and then submit your CSV file.

**Comment by moingshaikh** [comment]
Hello, 

I am not sure where to ask for general help regarding extension installation, hence posting it here.

When trying to load this extension in Chrome, I am getting this error:

**"Manifest file is missing or unreadable. Could not load manifest."**
![err](https://user-images.githubusercontent.com/7282553/75511072-00a65280-5a13-11ea-8351-7360d3721816.png)

I would appreciate any help or if someone can point me to correct forum place where I can ask for help.

**Comment by dpalauzov** [comment]
Hello,
I have the same issue and refresh does not fix it. is there any other workaround?
Thanks!

**Comment by noitcudni** [comment]
@dpalauzov Did it show you an error count at the end? Can you send me a screenshot and email me your CSV file?

**Comment by dpalauzov** [comment]
@noitcudni absolutely nothing happens when I select my csv. no error, no action.

**Comment by advancedperiodontics** [comment]
@dpalauzov @noitcudni 

I was able to fix this bug by doing a hard refresh (cntrl+f5), and it then asked me to set my language to English.  After doing that the application worked normally.
