### ISSUE TITLE
Some problems with Csv file

### ISSUE THREAD

**Issue by MariaValdivia** [noitcudni/google-webmaster-tools-bulk-url-removal#58]
Good morning!
Would you help us?
We bought the extension, the last friday. We need remove 1033 Toxics Urls.
When we submit CSV file, the extension mark some error, 14 specifically. If we delete this first 14 mistakes, when we submit the new CSV file, appears 14 new errors.

We send you the Csv errors file.

Best regards!

**Comment by noitcudni** [comment]
Yes, I'm more than happy to help. Where did you send your csv file to? I didn't see it. Try lihster.developer@gmail.com

**Comment by metalechala** [comment]
Hello, I bought the extension, followed the instructions, loaded the CSV file but nothing happened. I just get the error counter increasing. Please Help. I need to remove over 2000 URLs.

Thank you

**Comment by metalechala** [comment]
My bad. I was doing it all wrong. It worked perfectly.
