### ISSUE TITLE
Publish to web store

### ISSUE THREAD

**Issue by fregante** [noitcudni/google-webmaster-tools-bulk-url-removal#6]
Can you publish it to the Chrome Web Store? If you don't mind I can do it on my account.

**Comment by noitcudni** [comment]
sure. I can do that over the weekend.

Lih

**Comment by fregante** [comment]
Sounds good! Thanks!

**Comment by mindbreaker** [comment]
I don't think this is a chrome extension, that will go through the approval process of the Chrome Web Store.
