### ISSUE TITLE
A removal request for this URL has already been made.

### ISSUE THREAD

**Issue by Koulouridhs** [noitcudni/google-webmaster-tools-bulk-url-removal#60]
Can he have an update for this? https://prnt.sc/rfabab

Thanks in advance!

**Comment by noitcudni** [comment]
You are referring to google-webmaster-tools-bulk-outdated-content-removal not this repo, correct?

**Comment by Koulouridhs** [comment]
> You are referring to google-webmaster-tools-bulk-outdated-content-removal not this repo, correct?

Hi, for this one WebMasterTools: Bulk Outdated Content Removal
I had downloaded from github not from store
