### ISSUE TITLE
como eliminar las URLS

### ISSUE THREAD

**Issue by kristiangomez00** [noitcudni/google-webmaster-tools-bulk-url-removal#61]
como eliminar las URLS webmaster tools en LA NUEVA HERRAMIENTA 
GOOGLE SEARCH CONSOLE  pero en este año 
no me carga el archivo alguien me podria indicar estos pasos

**Comment by noitcudni** [comment]
So, via google translate, I think you are asking how to use the new extension? You'll need to click on the green trash can. In the popup, you'll find the `Submit CSV file` button.

**Comment by kristiangomez00** [comment]
friend noitcudni does not work with the new version google console 2020
and the worst I even bought the extension and it has not helped me to remove the urls
I would like you to make a video with the new version google 2020 console 2020 I would appreciate it and send it to my email
crcasago40@gmail.com

**Comment by noitcudni** [comment]
It does work with the new google search console. Which version are you using? I did inadvertently introduced a bug. I'm more than happy to help.

Please do the following. 
1. Take a screenshot of your removal page.
2. Right click on anywhere on the page. Select Inspect to bring up the developer console. Inside the developer console, click on the console tab.  Reload the page and take a screenshot of the output.

Send me those screenshots to lihster.developer@gmail.com. Or post them here.
