### ISSUE TITLE
Tool csv submit works well first, after some URLS submited it stops

### ISSUE THREAD

**Issue by josepbbs** [noitcudni/google-webmaster-tools-bulk-url-removal#62]
Tool csv submit works well first, after some URLS submited it stops

I switched already to english language,
I refreshed the browser and tried again
I claeared browser cache

Any ideas about what might be happening please?

**Comment by noitcudni** [comment]
Yes, a new version should address this problem. In short, it's not waiting long enough in between actions. 
I'm just waiting on google to approve the new version.

**Comment by prezlopp** [comment]
I have the same problem as josepbbs.

When will the extension be updated? I bought it on Monday 16th

**Comment by noitcudni** [comment]
Hmm..Please email me at lihster.developer@gmail.com.

**Comment by noitcudni** [comment]
Can you provide me with a screenshot of the removal page? @prezlopp

**Comment by josepbbs** [comment]
Hi,
Some updates about this issue?

**Comment by noitcudni** [comment]
version 1.4 should fix this issue. Is this not the case for you?

**Comment by josepbbs** [comment]
testing version 1.4 and not working for me
after few minutes working it suddently stops running...

**Comment by noitcudni** [comment]
What's your downlink speed? Also, can you ping me directly at lihster.developer@gmail.com?

**Comment by josepbbs** [comment]
Hi,
The extension is running very very extremely slow...
Any news about when google will approve the new version?
now is impossible to progress this way

**Comment by noitcudni** [comment]
1.6 is out now. By the way, is your language set to English?

**Comment by josepbbs** [comment]
Yes, I tried all this:

- The language is set to English
- New version 1.6 installed on my Chrome browser
- I cleared cache and cookies, 
- I restarted the pc and the browser
- I tested in direct ethernet conection 300M (not in wifi) 
- I reinstaled the extension several times...and the issue persists
- I tried in other machines with windows and Mac OS

the process between submits are too extremely slow, by 8/10 submits in 1 hour
it's faster when submitting manually one per one...

I do not what to do more...

Is anybody more experiencing the same trouble?

**Comment by noitcudni** [comment]
Can you bring up your developer console?
Right click anywhere on the page and click on inspect. Then, click on
console.

Click on the clear cache button in the extension. Refresh the page. Submit
your csv file.
Take a screenshot of the console and send it to me.

Lih

**Comment by josepbbs** [comment]
yes of course
these afre the messages from the cosole
I send through email a screen capture also

Using this console may allow attackers to impersonate you and steal your information using an attack called Self-XSS.Do not enter or paste code that you do not understand.
content-script.js:740 CONTENT SCRIPT: init
content-script.js:458 "single-node: " nil
content-script.js:458 "nodes: " ()
content-script.js:705 CONTENT SCRIPT: starting message loop...
content-script.js:458 "CONTENT SCRIPT: process-message!: " {:type :done-init-victims}
content-script.js:458 "CONTENT SCRIPT: process-message!: " {:removal-method "remove-url", :type :remove-url, :victim "https://www.bbsport.com/rrs-equipamiento/4861-28073-camisa-ignifuga-fia-rrs-flex.html", :url-type "url-only"}
content-script.js:458 "handling :remove-url"
content-script.js:458 "most-recent-removal: " "https://www.bbsport.com/en/2072-accessories-bmw-serie-e8x"
DevTools failed to parse SourceMap: chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/iframe_handler.map
DevTools failed to parse SourceMap: chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/content.map

**Comment by josepbbs** [comment]
yes of course

I send a screen capture through email

**Comment by josepbbs** [comment]
Having a look to the console I discovered an message from an extension that could have been interfering on the removal tool extension
I have removed that, restarted and now I am triying again, 
I will update next steps

**Comment by noitcudni** [comment]
Nothing jumped out at me from your screenshot. If it's not too much trouble, can you take the same screenshot again, except this time press the view cache button from the extension first.

FYI, I have not come across other users with your issue.  Let me know if another extension did, in fact, cause the slow down.

**Comment by josepbbs** [comment]
Unfortunately, after disabling some extensions, the Removal tool keeps going extremely slow
I send another screencapture this time without pressing view cache button

**Comment by noitcudni** [comment]
The latest version fixes this performance issue.
