### ISSUE TITLE
Installation not possible : manifest.json missing

### ISSUE THREAD

**Issue by Stonetatara** [noitcudni/google-webmaster-tools-bulk-url-removal#63]
Hi,

I tried today to install your extension, but I had this error message : "manisfest.json file missing".
I checked the directory: this file is indeed missing.

Did you know that ?

Thank you for your help
Cheers

**Comment by 4lxndr** [comment]
If you run the installation the final release is inside of the folder `release`. E.g.: `google-search-console-bulk-url-removal/releases/google-webmaster-tools-bulk-url-removal-0.1.0-SNAPSHOT#`
