### ISSUE TITLE
Extension not working on different accounts

### ISSUE THREAD

**Issue by neildacayan** [noitcudni/google-webmaster-tools-bulk-url-removal#64]
I bought the under two accounts. Only one was working. Please help me fix this issue.

**Comment by noitcudni** [comment]
What are the versions of those two extensions?

**Comment by neildacayan** [comment]
1.4. If I have an account synced in chrome and use a different account in GSC, should the extension still work?

**Comment by noitcudni** [comment]
Don't know as I've never tried that. 
For the account that doesn't work, can you take a screenshot of your removal page.

Also, right click on anywhere on the page and select inspect to bring up your developer console.
Click on the console tab. Submit your csv file and send me a screenshot of the developer console.

**Comment by neildacayan** [comment]
Here's the screenshot - https://imgur.com/ZCtEt0g

**Comment by noitcudni** [comment]
Thanks for the screenshot. I introduced a bug in version 1.4  where if your account hasn't submitted a URL for removal, it wouldn't work.

The upcoming version will fix that. 

In the meantime, you can first submit a URL for removal manually. Then, the extension should work as expected.

**Comment by noitcudni** [comment]
Did it work?

**Comment by neildacayan** [comment]
Hi, sorry for the late response. It is now working as long as there is a first entry submitted.

**Comment by noitcudni** [comment]
Good to hear that it works for you. If you don't mind, would you please update your review on the webstore?

**Comment by neildacayan** [comment]
Sure thing. Any timeline for the release of the new update?

**Comment by noitcudni** [comment]
It all depends on when google decides to approve my update. It usually takes about 24 hours, but this one has taken several days.

**Comment by noitcudni** [comment]
Just to be clear. You don't need to do this workaround every time. You just need to do this once so that there's at least one submitted removal entry showing up in the table.

**Comment by noitcudni** [comment]
Also, just checked. Version 1.5 is out.
