### ISSUE TITLE
Automatically accept warning message

### ISSUE THREAD

**Issue by domantasg** [noitcudni/google-webmaster-tools-bulk-url-removal#65]
Hey,

I have thousands of subdomains to remove. I use prefix url type. The problem is that it always asks for confirmation: https://prnt.sc/rnz0au and then stops

How to automate this and accept all?

**Comment by noitcudni** [comment]
Oh wow, you want to block the entire subdomain? I suppose I'm not handling
that. Can you send me your csv file?

**Comment by noitcudni** [comment]
Nevermind my last request. Version 1.6 will support removals of an entire
site. It should be approved by google sometime next week.

**Comment by domantasg** [comment]
Works perfectly! You can close this issue. Thanks!
