### ISSUE TITLE
Extension is not working

### ISSUE THREAD

**Issue by ashleykevin** [noitcudni/google-webmaster-tools-bulk-url-removal#68]
I installed the extension to chrome but when I go to my google search console removal URL over there it's not showing the option to upload a file I refreshed it many times but still, the extension is not working please help me

**Comment by noitcudni** [comment]
Did you click on the green trash can? You should be able to find the submit button in the popup after clicking on the green trash can.

**Comment by ashleykevin** [comment]
Yes, sir, I clicked on it many times but submit button is appearing in the popup you can see the screenshot please help me
![Capture](https://user-images.githubusercontent.com/64076557/79887960-54cd2200-8419-11ea-9239-2ef9772eb0af.JPG)

**Comment by ashleykevin** [comment]
Yes, sir, I clicked on it many times but submit button is appearing in the popup you can see the screenshot please help me
![Capture](https://user-images.githubusercontent.com/64076557/79887960-54cd2200-8419-11ea-9239-2ef9772eb0af.JPG)


> Did you click on the green trash can? You should be able to find the submit button in the popup after clicking on the green trash can.

Yes, sir, I clicked on it many times but submit button is appearing in the popup you can see the screenshot please help me
![Capture](https://user-images.githubusercontent.com/64076557/79887960-54cd2200-8419-11ea-9239-2ef9772eb0af.JPG)

**Comment by noitcudni** [comment]
That's a really old version. Please update it.

**Comment by ashleykevin** [comment]
> That's a really old version. Please update it.

How to update it? please tell me sir

**Comment by noitcudni** [comment]
How did you install it? Did you purchase it from the google webstore?

**Comment by ashleykevin** [comment]
> How did you install it? Did you purchase it from the google webstore?

No I downloaded it I didn’t purchased it

**Comment by noitcudni** [comment]
I'm guessing that was a while ago?
In that case, you'll have to follow the instructions here: https://github.com/noitcudni/google-search-console-bulk-url-removal.

**Comment by noitcudni** [comment]
I'm closing this issue since it's not really a bug.
