### ISSUE TITLE
[Feature Request] Bulk "Fetch as Google"

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [noitcudni/google-webmaster-tools-bulk-url-removal#7]
Your script is awesome man, I wish you could make something similar for fetch as google section! Thanks anyway <3

**Comment by noitcudni** [comment]
Thank you.
What did you mean by "Fetch as Google"?

Lih

**Comment by Sh4d0wHunt3rX** [comment]
![image](https://cloud.githubusercontent.com/assets/15929497/22532568/39dbba80-e8e8-11e6-9a0f-70711140ecaa.png)

This section, I mean.

**Comment by Sh4d0wHunt3rX** [comment]
However after fetching 10 links, google captcha will appear. I think it would be great if you make something similar for this part and for example when google captcha appears, it pauses the automation and we fill the checkbox and then resume the automation :)

**Comment by noitcudni** [comment]
@amiremami Check out https://github.com/noitcudni/google-webmaster-tools-bulk-fetch-as-google.
Better late than never.

**Comment by Sh4d0wHunt3rX** [comment]
OMG! Thank you so much my friend <3
Will look in to this, really appreciate your effort.

**Comment by noitcudni** [comment]
No problem. Let me know if you run into any issues.
