### ISSUE TITLE
One removal added- then stops

### ISSUE THREAD

**Issue by keithbruss** [noitcudni/google-webmaster-tools-bulk-url-removal#70]
WebMaster Tools - Bulk URL removal 1.7 (built yesterday)

Tested on 
Windows 10 
Chrome Version 80.0.3987.163 (Official Build) (64-bit)

I built the plugin from source on github.

I am logged into Chrome.  I created a list of urls one per line with each line starting:

https://domain.com/string_to_be_removed1
https://domain.com/string_to_be_removed2
etc

Saved as a text file or CSV file.  UTF-8 encoded.  Line endings are unix LF or windows CRLF with same results.

The problem is only the first URL from the list is added to removals.  It stops after 1.

I tried this on a few different virtual machines with the same results. 

Thanks

**Comment by keithbruss** [comment]
I did receive these warnings:

OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Compiling ClojureScript...
Compiling ["resources/release/compiled/background.js"] from ["src/background"]...
Successfully compiled ["resources/release/compiled/background.js"] in 16.642 seconds.
Compiling ["resources/release/compiled/popup.js"] from ["src/popup"]...
WARNING: domina is a single segment namespace at line 1 resources/release/compiled/popup/domina.cljs
WARNING: *debug* not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic *debug* or change the name at line 111 resources/release/compiled/popup/domina.cljs
Successfully compiled ["resources/release/compiled/popup.js"] in 20.359 seconds.
Compiling ["resources/release/compiled/content-script.js"] from ["src/content_script"]...
WARNING: domina is a single segment namespace at line 1 resources/release/compiled/content-script/domina.cljs
WARNING: *debug* not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic *debug* or change the name at line 111 resources/release/compiled/content-script/domina.cljs
Successfully compiled ["resources/release/compiled/content-script.js"] in 14.766 seconds.


Built using:
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode)

**Comment by jknechtl** [comment]
I have the same issue and Errors, built on MacOS Catalina. Loads and execute just one line of CSV, then stops with no message in console.

When I click on "View cache" nothing happens.

**Comment by noitcudni** [comment]
You need to bring on the developer console that's bound to the popup in order to see the output from "View cache". Bring up the extension popup and right click -> inspect. 

In terms of executing only one line of CSV, can you try clicking on "Clear cache" and reload the page and try again.

**Comment by keithbruss** [comment]
This log is scrubbed of the actual links but this is a test of 5 links and this is what i get.  I've tried every file format I can think of, UTF-8 ANSI etc.  Different line encoding. etc.

```
"file-content: " "https://domain.com/slug1\r\nhttps://domain.com/slug2\r\nhttps://domain.com/slug3\r\nhttps://domain.com/slug4\r\nhttps://domain.com/slug5"
popup.js:1165 about to call :init-victims
popup.js:702 {"https://domain.com/slug1" {"idx" 0, "removal-method" "remove-url", "remove-ts" nil, "status" "removing", "submit-ts" 1588016719713, "url-type" "url-only"}, "https://domain.com/slug2" {"idx" 1, "removal-method" "remove-url", "remove-ts" nil, "status" "pending", "submit-ts" 1588016719714, "url-type" "url-only"}, "https://domain.com/slug3" {"idx" 2, "removal-method" "remove-url", "remove-ts" nil, "status" "pending", "submit-ts" 1588016719716, "url-type" "url-only"}, "https://domain.com/slug4" {"idx" 3, "removal-method" "remove-url", "remove-ts" nil, "status" "pending", "submit-ts" 1588016719719, "url-type" "url-only"}, "https://domain.com/slug5" {"idx" 4, "removal-method" "remove-url", "remove-ts" nil, "status" "pending", "submit-ts" 1588016719720, "url-type" "url-only"}, "poison-pill" {"idx" 5, "removal-method" "**D0N3-FL@G**", "remove-ts" nil, "status" "pending", "submit-ts" 1588016719722, "url-type" "url-only"}}
popup.js:702 "bad-victims: " ()
```

I can only get it to execute one line of CSV.  I've tried clearing cache.  I tried reloading the page.  I've actually tried this on two linux desktops and two windows 10 desktops.  I even did a fresh install of windows 10 and chrome.    Any suggestions are greatly appreciated.

**Comment by noitcudni** [comment]
Send me a screenshot of your developer console's output to lihster.developer@gmail.com. More info the better.

**Comment by keithbruss** [comment]
latest update fixes this issue.  Thanks to noitcudni for a great response.
