### ISSUE TITLE
Only able to upload 20 URLs at once

### ISSUE THREAD

**Issue by amandeepwebspero** [noitcudni/google-webmaster-tools-bulk-url-removal#72]
I have around 6000 pages to deindex and only 20 URLs are getting processed at a time. Please fix this or let me know refund process

**Comment by noitcudni** [comment]
While the extension is running, you can't tab away. You can open up a new browser window, however. Let me know if that's the problem.

If not, can you send me your csv file? Is it stopping at exactly 20 URLs consistently?

**Comment by amandeepwebspero** [comment]
I changed the tab after uploading the file but it was processing only 20-25 URLs.

However, I will check it again without changing the tab. I will let you know if the problem persists.

Thanks
