### ISSUE TITLE
Does it works with the new Search Console?

### ISSUE THREAD

**Issue by davidperezgar** [noitcudni/google-webmaster-tools-bulk-url-removal#73]
Hello, 
I'm trying to use it with the new Search Console, but the extension seems that does not work.

Could you please tell me what to do?

**Comment by noitcudni** [comment]
Please describe your problems in more detail.

Can you provide a screenshot? 
Is the language setting set to English?
Did it run at all? Did it indicate how many errors it encountered? Were you able to download the error csv from the extension popup?

**Comment by noitcudni** [comment]
And yes, it is built to work with the new search console.

**Comment by davidperezgar** [comment]
My language is Spanish, does it affect?

**Comment by davidperezgar** [comment]
I don't see the button...

![Captura de pantalla 2020-05-29 a las 10 35 32](https://user-images.githubusercontent.com/10096360/83239500-456b9200-a198-11ea-96cc-8e1b7ec6e6e1.png)

**Comment by davidperezgar** [comment]
I don't see the button... 
![Removals](https://user-images.githubusercontent.com/10096360/83239620-7946b780-a198-11ea-93ac-2c87e7774141.jpg)

**Comment by noitcudni** [comment]
Looks like the extension set your language to English, so we are good on the front.

Click on the green trash can, and you'll find a blue "Submit CSV" button. Click on that blue button to kick start the whole process.
