### ISSUE TITLE
Got Error: Manifest file is missing or unreadable

### ISSUE THREAD

**Issue by Ahmadkazmmi** [noitcudni/google-webmaster-tools-bulk-url-removal#75]
First I Download the file and Extract it, Then I was adding through Load Unpacked. I got this error.

**Comment by KorayTugberk-g** [comment]
I have the same issue? Isn't this a free tool?

**Comment by Ahmadkazmmi** [comment]
> I have the same issue? Isn't this a free tool?

I didn't get Any Free One.

**Comment by Josemialarc** [comment]
Yes, I have the same issue.

I downloaded the entire folder, unzipped it.

Later I went to chrome extensions, enable the tag "Processed mode" and when trying to do the unzipped load it gave me the error "the manifest file is missing"

¿What I have to do?¿Where is the step that I forgot?

**Comment by noitcudni** [comment]
To compile the source code, follow the instructions in the readme.
If you find that's too much trouble, you many purchase  it directly from Google webstore https://chrome.google.com/webstore/detail/webmaster-tools-bulk-url/pmnpibilljafelnghknefahibdnfeece.
