### ISSUE TITLE
Received "Download Error CSV"

### ISSUE THREAD

**Issue by joseph-beyond** [noitcudni/google-webmaster-tools-bulk-url-removal#76]
I downloaded this extension directly from the Chrome Web Store. After clicking on the "submit CSV file", I received the popup that the bulk removal was "done". Nothing was added to the removal list. I refreshed the page several times, attempting to resubmit the CSV file. It hasn't worked any of the times that I've submitted the CSV file.

I continue to receive: "Error Count: 1".

**Comment by noitcudni** [comment]
Did you download the "error csv" by clicking on the "Download Error CSV"? Email that over to me once you have it. lihster.developer@gmail.com

**Comment by joseph-beyond** [comment]
I ended up figuring out the issue with the CSV sheet I uploaded. Thank you for following up with me.
