### ISSUE TITLE
proccess not start

### ISSUE THREAD

**Issue by abdulbasetbasher** [noitcudni/google-webmaster-tools-bulk-url-removal#78]
I got this when I inspect the extension

`about to call :init-victims`

and nothing happen

**Comment by noitcudni** [comment]
Did it show you an error count? Could you download the error CSV? If not, send me your csv input file to lihster.developer@gmail.com

**Comment by abdulbasetbasher** [comment]
i add header url to csv , now i see

"init-errors: " {:type :init-errors, :bad-victims ()}

**Comment by noitcudni** [comment]
No, did it show you an error count on the extension button itself? If not, send me your csv file.

**Comment by abdulbasetbasher** [comment]
> No, did it show you an error count on the extension button itself? If not, send me your csv file.

i sent you my csv

**Comment by noitcudni** [comment]
Haven't gotten it yet. In the meantime, please read the CSV Format section in the readme.

**Comment by abdulbasetbasher** [comment]
```
url,removal-method
https://example.com/view/jA00nF-FL1c/amp.htm,remove-url
https://example.com/view/VfIct9fz8jQ/amp.htm,remove-url
https://example.com/view/Syt577ayVQA,remove-url
https://example.com/view/aUsZFp61f70/amp,remove-url
https://example.com/results?q=trending+news,remove-url
https://example.com/view/WcMCPpQibGI.htm,remove-url
https://example.com/view/Oj-HtO9vLTc/amp.htm,remove-url
https://example.com/view/xCXhprhRux4.htm,remove-url
```

**Comment by noitcudni** [comment]
Get rid of the header.

**Comment by abdulbasetbasher** [comment]
i removed the header and it works,  thank you
