### ISSUE TITLE
Manifest file is missing or unreadable

### ISSUE THREAD

**Issue by muhammadsajjad** [noitcudni/google-webmaster-tools-bulk-url-removal#79]
I have been using this extension in past but now i am trying to use it again. 

Initially, it is not available on Chrome Store as provided in the download URL. When i downloaded the ZIP file and unzipped it to upload the unpacked in Chrome Developer Mode, it says, Manifest file is missing or unreadable.  

Please have a look at the attached image. 

![2020-07-21_19-03-12](https://user-images.githubusercontent.com/1596185/88064362-9f7b4900-cb84-11ea-8afe-b246cb8e57b3.png)

I am looking forward for a resolution. 

Thanks

**Comment by noitcudni** [comment]
You can compile the code by following the instructions in the README. Or, you can purchase it on the webstore.
