### ISSUE TITLE
[Feature Request] Bulk Url Removal in unverified sites

### ISSUE THREAD

**Issue by ghost** [noitcudni/google-webmaster-tools-bulk-url-removal#8]
Google Search Console allows to remove outdated content in unverified sites:
https://www.google.com/webmasters/tools/removals

![ss](https://cloud.githubusercontent.com/assets/25534423/23080280/6ee24694-f550-11e6-9f1e-4a6e782c037e.png)

Is possible add Bulk Url Removal to unverified sites too?

Thank you.

**Comment by shendison** [comment]
No. Think about it, and you'll understand why this could never be possible under any circumstances...
