### ISSUE TITLE
Unable to download from Chrome Store

### ISSUE THREAD

**Issue by websolpro** [noitcudni/google-webmaster-tools-bulk-url-removal#80]
Hi,
I am unable to download extension from chrome store. Could you please tell me how i can install?
I have read your installation documents, but it is not working for me because i am beginner.  Please give me extension files, i will directly load in chrome. Thanks.

Regards,
FHS

**Comment by noitcudni** [comment]
Trying proxying through a server in the US or Europe.

**Comment by websolpro** [comment]
Hi,
Thank you for your reply. Yes, now i am using USA proxy it is asking me the price $15. I clicked on it. This button is saying "processing" and nothing happens. Can you please send me packed extension? so i will unpacked it and load in chrome directly. Thank you.

Regards,
Farrukh

**Comment by noitcudni** [comment]
OK, can you send me your purchase order?

**Comment by websolpro** [comment]
I clicked on purchsse than nothing happened. Button is saying processing.
  

  

  
  
 Best Regards, Farrukh H. Siddiqui Web Solution Provider Cell: +92-335-2345111 Email: admin@websolpro.com Homepage: www.websolpro.com  

  
  
  
  
  
>
