### ISSUE TITLE
Doesn't work with CSV file from Google Search Engine without editing

### ISSUE THREAD

**Issue by Andreas-T** [noitcudni/google-webmaster-tools-bulk-url-removal#82]
The CSV file that the Google Search Engine exports contains a column with the crawl date and this causes an error in the extension.
Preferably the extension should strip any extra columns and also strip any trailing semicolons that may be exported from a spreadsheet program after manually editing the list. (Google cannot match the URL if there is a trainling semicolon)

**Comment by noitcudni** [comment]
trailing semicolon? Does excel do that?

**Comment by Andreas-T** [comment]
I noticed that Apple Numbers do it if you delete a column and save as CSV. Need to clean it up in a text editor afterwords.
I tested it now in Excel and there is no trailing separator so no need to edit it afterwords.
Still, I suggest that the plugin ignores the second column and separator from the Google Search Console export so that no editing is needed.

**Comment by noitcudni** [comment]
Not everyone is creating the csv file directly from Google Search Console export. I'm not too keen adding complexities based on that assumption.

**Comment by Andreas-T** [comment]
I can't speak for others, but I bought the extension specifically to try to deal with thousands of indexed spam pages after a hack on a CRM plugin. There is no other realistic way to create those CSV files than to export them form the search console, a thousand items at a time. I would imagine many uses cases are like mine and I assumed the extension was tailored to the export files generated by Google as it's specifically for bulk removal. 
I would think it wouldn't be complicated to do this with a simple regex in the extension and it would be transparent for the user whether it's a single or multi column file. Strip everything except the first column. Anyway, that's my input and you of course do what you want.

**Comment by noitcudni** [comment]
As it stands, the second and the third columns are being used in my plugin.
Please refer to the readme.

Some folks grab a list of erroneous urls from their access log.

While it may be seemingly simple to detect a date string and strip it, I'm
more concerned with the unforeseen impacts.
Currently, the extension does detect when something is amiss and shows an
error count on the extension button.
Should there be an error, the user can download an error report and figure
out from there.

In terms of manually removing a column, that should be quick and relatively
painless in any spreadsheet software.
