### ISSUE TITLE
Feedback: Daily submission quota reached at 1000 submits with new Search-Console

### ISSUE THREAD

**Issue by mkonvolut** [noitcudni/google-webmaster-tools-bulk-url-removal#83]
Hi @noitcudni 
You wanted to get feedback for "Daily quota reached".

I managed to submit 988 url:s with the plugin before reaching the daily quota. I had manually submitted approx 10 urls:s before that so the total quota seem to be 1000 url:s per day.

I installed the plugin from Github download and then compiling it myself.

**Comment by noitcudni** [comment]
Thanks for bringing this to my attention. Looks like google brought the quota back.
