### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [noitcudni/google-webmaster-tools-bulk-url-removal#85]
Unfortunately, it seems it's not working anymore, can you please check this on Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by noitcudni** [comment]
I see that you closed the issue. So, it's no longer a problem?

**Comment by Sh4d0wHunt3rX** [comment]
No, sorry my bad : )
