### ISSUE TITLE
"Remove all URLs with this prefix" option missing

### ISSUE THREAD

**Issue by haznac** [noitcudni/google-webmaster-tools-bulk-url-removal#86]
You really should consider adding an option where one can select "Remove all URLs with this prefix" instead of having to be stuck with "Remove this URL only". I'm trying to remove URLs indexed by a Japanese keyword hacker with a certain pattern. "Remove all URLs with this prefix" would save me a lot of time and headache.
![image](https://user-images.githubusercontent.com/71563515/93672331-2c089180-fa78-11ea-8e27-95a33fa60bb0.png)

Thanks,

**Comment by noitcudni** [comment]
Please refer back to README's CSV Format section. It can already do what you are asking.

**Comment by haznac** [comment]
> Please refer back to README's CSV Format section. It can already do what you are asking.

Got it. Thanks!

**Comment by noitcudni** [comment]
Do you mind changing your 4 star to 5 since it does handle prefix? Thanks.
