### ISSUE TITLE
Removes only 1 url

### ISSUE THREAD

**Issue by shiska420** [noitcudni/google-webmaster-tools-bulk-url-removal#87]
If I create a CSV file with a list of urls, it uploads it as one big long url.  It does not separate the URLs.   I've tried creating a csv file with txt edit as well as xCell.  Each time it uploads 1 big huge long string of all the URLs combined. 

I just spent $15 on this, I have no idea how to return it and it does not work. 

I'd like to either be told how to fix this issue or a refund. 

Thanks
Ryan

**Comment by noitcudni** [comment]
Please send me your csv file.
The problem is that it's not handling the carriage enter from whatever
program you used to generate your CSV file.

Lih

**Comment by noitcudni** [comment]
And Please update your one star review once I fix your csv file.

**Comment by noitcudni** [comment]
It's fixed for good in code
