### ISSUE TITLE
Bulk remover, manifest file is missing or unreadable

### ISSUE THREAD

**Issue by Bumblebee888** [noitcudni/google-webmaster-tools-bulk-url-removal#88]
Hi, What to do?

Failed to load extension
File
~\OneDrive\Desktop\google-search-console-bulk-url-removal-master
Error
Manifest file is missing or unreadable
Could not load manifest.

**Comment by noitcudni** [comment]
Please follow the instructions on the readme. If that still doesn't work, you can purchase it on the webstore: https://chrome.google.com/webstore/detail/webmaster-tools-bulk-url/pmnpibilljafelnghknefahibdnfeece?hl=en-US
