### ISSUE TITLE
I am getting Manifest Issue

### ISSUE THREAD

**Issue by sayandutta123** [noitcudni/google-webmaster-tools-bulk-url-removal#89]
Please help me with this tool. When I am going to load the unpacked extension it shows like this.

Manifest file is missing or unreadable
Could not load manifest.

**Comment by noitcudni** [comment]
Please follow the instructions in my README. If that doesn't work for you, you can always purchase it on the webstore.

**Comment by kk43man** [comment]
yes 
i am also getting same error.
