### ISSUE TITLE
Domain URL added in the beginning

### ISSUE THREAD

**Issue by ChristerG** [noitcudni/google-webmaster-tools-bulk-url-removal#9]
I have an issue with the Bulk URL Removal tool. When I use it the URLs gets wrong. I have an URL that looks like this:
http://xxxx.yyyy.com/?s=zzzzzzzz
When the Bulk URL Removal tool have uploaded the URL from the txt file, the domain URL is added in the beginning, so it looks like this:
http://yyyy.com/http://xxxx.yyyy.com/?s=zzzzzzzz
![skarmavbild 2017-03-14 kl 12 12 48](https://cloud.githubusercontent.com/assets/22372488/23941371/dd0f9028-0968-11e7-96be-be184f18912b.png)

**Comment by ChristerG** [comment]
I've found the solution to my problem. Since I was trying to remove subdomain URLs the domain adress was added in the beginning. To solve the problem I had to add each subdomain as a separate property in Google Search Console, and then run the URL removal tool in each property for their respective subdomain URLs.

**Comment by rushhourmarketing** [comment]
The tool is not working for me anymore at all. On Chrome 57... what are you using?
