### ISSUE TITLE
Nothing seems to respond

### ISSUE THREAD

**Issue by cobbernet** [noitcudni/google-webmaster-tools-bulk-url-removal#91]
Hi,

Im on my console removal page, with the extention open. I upload a csv file with one column titled URL and each url to be removed in that column. I click upload csv, select the csv and nothing happens.

**Comment by noitcudni** [comment]
send me your csv file

**Comment by cobbernet** [comment]
Thanks for swift reply!

see attached :)

**Comment by noitcudni** [comment]
I don't believe that it's showing up under Github issue. Please email the csv file directly to lihster.developer@gmail.com.

**Comment by cobbernet** [comment]
So removed the headers
Now the csv is a single column of URLs in 1, followed dirctions clicked upload csv. Nothing happens :(

**Comment by cobbernet** [comment]
Also not, the view cache button does nothing as well.

**Comment by noitcudni** [comment]
I will take a look in 30 minutes

**Comment by cobbernet** [comment]
Thanks, great support. Very prompt

**Comment by noitcudni** [comment]
I believe that refreshing your google search console should make the problem go away.
