### ISSUE TITLE
paid version not working

### ISSUE THREAD

**Issue by HBARI58** [noitcudni/google-webmaster-tools-bulk-url-removal#93]
I have paid version of this tool, yet asking me for the licencsed key Today tool stopped working and asking for licensed key of the tool.
![image](https://user-images.githubusercontent.com/75021707/100224277-a0f9bb00-2f42-11eb-87d3-82071acf2b79.png)

**Comment by noitcudni** [comment]
I had to migrate to a 3rd party payment system. Please ping me directly at lihster.developer@gmail.com.

**Comment by noitcudni** [comment]
Email me the google payment email.

**Comment by HBARI58** [comment]
Done

**Comment by noitcudni** [comment]
I believe this is resolved via email.
