### ISSUE TITLE
Already Bought but no License Key

### ISSUE THREAD

**Issue by dfa457** [noitcudni/google-webmaster-tools-bulk-url-removal#95]
Hi,

I bought this extension on 7th february (CWS.1527-0001-4989-82537). Recently it has been updated and asking license key. I never received license key to use it. Can you please let me know how to use the url removal again?

Thanks!

**Comment by noitcudni** [comment]
Please email me directly at lihster.developer@gmail.com

**Comment by noitcudni** [comment]
This is resolved via email.

**Comment by dfa457** [comment]
Hi,

Extension bulk removal stopped working just today. I tried with some csv
files but no signal of removing. What can I do?

Many thanks

Daniel

**Comment by noitcudni** [comment]
You can try uninstall and reinstall it.  Also, try refresh the page before
submitting the csv file.
