### ISSUE TITLE
Nothing happens even after page refresh

### ISSUE THREAD

**Issue by CodeHotDog** [noitcudni/google-webmaster-tools-bulk-url-removal#97]
I have a csv of urls in the format as requested. Just the urls in column 1. Go to search console, go to removals, hit the green upload icon, select the csv and nothing happens. I refresh the page and same thing.

Ideas? Using the extension on Windows 10, Chrome Version 86.0.4240.198 (Official Build) (64-bit). Have restarted Chrome and no luck.

**Comment by noitcudni** [comment]
Can you send me your csv file to lihster.developer@gmail.com?

**Comment by CodeHotDog** [comment]
There appeared to be a extension conflict so I installed this plugin https://chrome.google.com/webstore/detail/disable-extensions-and-ap/abmoaeegegigmhgfmdmlhkoghibgkpkj/related?hl=en

then whitelisted the Google Bulk URL Removal extension, and everything is working great now! Very good extension! Thank you.
