### ISSUE TITLE
I didnt get any invoice / email where the license key is

### ISSUE THREAD

**Issue by LuisWaukin** [noitcudni/google-webmaster-tools-bulk-url-removal#99]
Hello,

I had purchased this Google Chrome extension at 19-11-2019, but unfortunately, I didnt get the license key in my invoice email. Where can I find that? I need to use it but when I am trying to log into it, there is a login process that I can't complete due to that issue.

My email is: luis@waukin.es
My order number is: CWS.7341-8223-5492-93822

I didnt get any email with the info about my license, so therefore I can't login into the tool.

**Comment by noitcudni** [comment]
Check your email. Should be resolved now.
